### ISSUE TITLE
rEFInd script FAQ

### ISSUE THREAD

**Issue by eight85** [jlobue10/SteamDeck_rEFInd#1]
Have you tested what happens with new updates, switching from beta and stable updates vice versa? In the past I have had issues maintaining rEFInd on desktop linux with os updates were released. Does this setup support secure boot and what versions of windows does your script support?

**Comment by jlobue10** [comment]
Updates for both SteamOS and Windows 11 have worked fine for me and have not corrupted the rEFInd setup. Windows 10 and 11 are supported by the installation script. As for whether or not Secure boot is supported, that is more of a question for the rEFInd developer. This script is just meant as an easy way to have a proper, simple and clean rEFInd setup for the Steam Deck that does not require disabling Windows Updates to function properly. I can test and update the script once secure boot is supported and enabled via the BIOS, if and when that happens. If I'm able to get it working, I will either incorporate that into the main installation script, or make a separate script for installation with secure boot enabled.

**Comment by eight85** [comment]
How is booting Windows 11 without secure boot possible?

**Comment by jlobue10** [comment]
That is a question for Microsoft developers. I can tell you based on experience with the Steam Deck and Windows 11, that as long as you have firmware TPM enabled in the BIOS, then Windows 11 installs and runs just fine without any extra special setup or considerations. Without secure boot though, some games requiring certain anti-cheats will not currently run on the Steam Deck under Windows 11 (Fifa 23 and Valorant to name a few).

**Comment by eight85** [comment]
I appreciate all the info and I'm gonna close this as everything was answered. Thank you very much for taking the time and being so patient. Cheers
