### ISSUE TITLE
Is it possible to customize the icon position instead of putting it in middle?

### ISSUE THREAD

**Issue by getbiks** [jlobue10/SteamDeck_rEFInd#10]
I am looking to put my icon to custom position based on my wallpaper instead of in the centre. Is it possible to do so?

**Comment by jlobue10** [comment]
It may be possible, but I'm not sure how to do it. Maybe reach out to the developer of rEFInd itself. I read through his webpages and did not find a way to do this easily. Please refer to [OS icons](https://www.rodsbooks.com/refind/configfile.html#icons) and [themes](https://www.rodsbooks.com/refind/themes.html) for more info. My installation script provides a few free background options and some alternative icon choices, both of which require some `refind.conf` edits to take advantage of. That is the extent of customization that I've provided. Of course the options are really only limited to the end user's imagination though for backgrounds and icons. This script is meant more to get the bootloader functional. Ultimately final customization is up to the end user, if he or she wants to deviate from what I include.

**Comment by jlobue10** [comment]
Refer to rEFInd documentation. This does not seem like a trivial thing to accomplish. Closed.
