### ISSUE TITLE
Windows is not booting from Refind

### ISSUE THREAD

**Issue by imsofresh54** [jlobue10/SteamDeck_rEFInd#113]
Hey,

I've got issue with refind. It seems installing okay, but on the choose menu, when im selecting Windows, it shows error: 

"Invalid loader file!
Error: Not found while loading bootmgfw.efi"

Other thing, i paid attention to, that when I was going through tutorial, i cannot disable EFI entry, using "sudo efibootmgr -b XXXX -A" i got following error:

"Boot entry 3 not found
set active state for Boot0003: No such file or directory"

**Comment by jlobue10** [comment]
Are you able to boot into Windows if you go into BIOS and either use Window's EFI entry or try to boot from the Windows boot file manually?

**Comment by imsofresh54** [comment]
> Are you able to boot into Windows if you go into BIOS and either use Window's EFI entry or try to boot from the Windows boot file manually?

Yes, I am. It is listed in boot menu, boots with no issue.

**Comment by imsofresh54** [comment]
> Are you able to boot into Windows if you go into BIOS and either use Window's EFI entry or try to boot from the Windows boot file manually?

Yes, I am. It is listed in boot menu, boots with no issue.

**Comment by jlobue10** [comment]
Please show me your `refind.conf` file. `sudo nano /esp/efi/refind/rEFInd.conf`

**Comment by jlobue10** [comment]
Is Windows installed on the same internal drive as SteamOS, or on the SD card or USB drive?

**Comment by imsofresh54** [comment]
> Is Windows installed on the same internal drive as SteamOS, or on the SD card or USB drive?
It is installed on one SSD. Have no sdcard installed. 
![IMG_3117](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/f6c9db11-ce02-4933-8392-9ffc0e4f5a0f)

**Comment by jlobue10** [comment]
Can you show me the output of `efibootmgr`?

**Comment by jlobue10** [comment]
Also I see a problem in your screenshot... why does the config file have caps in the name? It should not. It should be all lowercase as I typed, and it should be installed that way properly with the install config button.

**Comment by imsofresh54** [comment]
> Can you show me the output of `efibootmgr`?

![IMG_3118](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/7274c547-b9d3-47ed-ac93-eadaba88ad20)

**Comment by imsofresh54** [comment]
> Also I see a problem in your screenshot... why does the config file have caps in the name? It should not. It should be all lowercase as I typed, and it should be installed that way properly with the install config button.

Like this?
![IMG_3119](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/2844f1fc-3e25-483e-8fa3-14d06bff3332)

**Comment by jlobue10** [comment]
Did you use `pacman` or Sourceforge installation source for the install rEFInd step? There is a new version on Sourceforge and I need to update that script, which would still be the preferred method (Sourceforge) imo.

**Comment by imsofresh54** [comment]
> Did you use `pacman` or Sourceforge installation source for the install rEFInd step? There is a new version on Sourceforge and I need to update that script, which would still be the preferred method (Sourceforge) imo.

I used Sourceforge source.

**Comment by jlobue10** [comment]
This is really strange as everything at least appears normal with the config file and efibootmgr entries, aside from the Windows entry not being disabled. I will have to see if I can replicate this.

**Comment by jlobue10** [comment]
How did you install the GUI?

**Comment by imsofresh54** [comment]
> How did you install the GUI?

![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/87b30a1b-bd35-4da5-9e65-f8b0be6680f5)

Using this command.

**Comment by jlobue10** [comment]
Okay... yes this could be the problem. Having two different EFI system partitions

**Comment by jlobue10** [comment]
Can you confirm that partition 1 is still the `/esp` partition for SteamOS?

**Comment by imsofresh54** [comment]
![Uploading IMG_3119.jpeg…]()


> Show me the output of `lsblk -f` please.

**Comment by imsofresh54** [comment]
> Show me the output of `lsblk -f` please.

![IMG_3119](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/12744951-6312-4891-9b94-a3f96075bfa0)

**Comment by imsofresh54** [comment]
> Show me the output of `lsblk -f` please.

![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/2c62e18c-9f12-4f9b-aeb4-6a62745bc0c3)

**Comment by jlobue10** [comment]
Yes, this is the problem... double EFI system partitions. Let me research something about a potential solution here. This deviates from a standard Windows dual boot installation where the Windows installer is smart enough to just install its boot files into the existing EFI system partition.

**Comment by imsofresh54** [comment]
> Yes, this is the problem... double EFI system partitions. Let me research something about a potential solution here. This deviates from a standard Windows dual boot installation where the Windows installer is smart enough to just install its boot files into the existing EFI system partition.

Oh, i see. Thank you so much for your time, im not sure i will be able to fix it myself.

**Comment by jlobue10** [comment]
I think if you follow the instructions [here](https://github.com/jlobue10/SteamDeck_rEFInd/issues/49) and point it to the proper partition 1 EFI system partition, that may be a workaround that works.

**Comment by jlobue10** [comment]
There is another potential solution here if we add a label (such as `WINDOWS_EFI`) to the WinDeckOS EFI partition and then add that in your refind config file above the Windows loader line as `volume WINDOWS_EFI`. I have seen that work in the past for these manual boot stanzas with multiple EFI system partitions.

**Comment by imsofresh54** [comment]
> There is another potential solution here if we add a label (such as `WINDOWS_EFI`) to the WinDeckOS EFI partition and then add that in your refind config file above the Windows loader line as `volume WINDOWS_EFI`. I have seen that work in the past for these manual boot stanzas with multiple EFI system partitions.

Yes! This actually helped! Thank you so much! 

Last one question, icon of Windows is now messsed up. 

Conf looks like this. 
![IMG_3126](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/7571a985-a7a3-4dfc-90ce-e9f83fc4c1af)
![IMG_3125](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/80fb75d4-6df9-4a0d-89cb-d43039fe18db)

**Comment by imsofresh54** [comment]
All fixed, ico path should be first. 

Thank you!

**Comment by jlobue10** [comment]
Awesome! I'm happy that you figured it out with my assistance.

**Comment by imsofresh54** [comment]
Hello sir, thank you for previous help. I currently setting up dualboot to another SD, and want to do it right way this time, can you please tell me if this is right order of things im doing. 

I reinstalled steam OS, and shrink SSD and made a new NTFS volume. Than installing Windows on that volume, and than install refind using GUI under SteamOS and good to go? 

Thank you!

**Comment by jlobue10** [comment]
On a different SD card?

**Comment by imsofresh54** [comment]
> On a different SD card?

I've already installed Win on it, ReFind later. Everything works great this time, but after I joining Windows, it by default running Windows later, so no refind menu appears. I've managed to fix it on my own deck, but cannot remember what i did. 

I did: 

sudo efibootmgr -b XXXX -A ( my boot win boot is 0004 ) But there was an error something like "No such file or directory" (I have no that other SD by hand until tomorrow) I did same thing under steam rescue iso, there was same error. I left it as it, told the guy i will fix it tomorrow. xD

Before it i've tried Easy UEFI under Windows, deleted boot option, and I could no more boot into OS, had to reinstall it. xD

**Comment by jlobue10** [comment]
Oh yes, thank you for refreshing my memory here. Since SteamOS 3.4, unfortunately that command has stopped working to disable the Windows EFI entry with `efibootmgr`. Running the proper `egibootmgr` command does work however if you boot into the latest live Ubuntu (or Kubuntu) 24.04 iso, or at least it worked for me the last time that I tried it.

**Comment by imsofresh54** [comment]
> Oh yes, thank you for refreshing my memory here. Since SteamOS 3.4, unfortunately that command has stopped working to disable the Windows EFI entry with `efibootmgr`. Running the proper `efibootmgr` command does work however if you boot into the latest live Ubuntu (or Kubuntu) 24.04 iso, or at least it worked for me the last time that I tried it.

I see. Will try it tomorrow than. Thank you!

**Comment by imsofresh54** [comment]
> Oh yes, thank you for refreshing my memory here. Since SteamOS 3.4, unfortunately that command has stopped working to disable the Windows EFI entry with `efibootmgr`. Running the proper `efibootmgr` command does work however if you boot into the latest live Ubuntu (or Kubuntu) 24.04 iso, or at least it worked for me the last time that I tried it.

I've made an bootable flash with Ubuntu 24.04, tryed command on my SD, still the same error. What im doing wrong again? 🤣
![IMG_3517](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/bb94f0e8-aceb-47bb-9056-82cd33d0199a)

**Comment by jlobue10** [comment]
That doesn't look like it's Windows from the SD card slot. Can you try deleting that entry and seeing if that actually works? `sudo efibootmgr -b 0006 -B`

**Comment by imsofresh54** [comment]
> That doesn't look like it's Windows from the SD card slot. Can you try deleting that entry and seeing if that actually works? `sudo efibootmgr -b 0006 -B`

No no, both Windows and Steam OS are on SSD, no SD card at all.

**Comment by jlobue10** [comment]
Okay, nevermind then. It's confusing if you use SD to refer to Steam Deck rather than the SD card slot. Don't delete it then. Maybe try Kubuntu 23.10, if you can find the live iso of it.

**Comment by imsofresh54** [comment]
> Okay, nevermind then. It's confusing if you use SD to refer to Steam Deck rather than the SD card slot. Don't delete that entry then. Maybe try Kubuntu 23.10, if you can find the live iso of it.

Yes, I got you confused, sorry I noticed it only now...

but heeeeeellll yeeeeah that worked!! 🤩 Hope Windows Boot Manager is gone forever. 😁
![IMG_3518](https://github.com/jlobue10/SteamDeck_rEFInd/assets/37051674/77318787-dc0d-4231-97fd-955f28e6bc65)

**Comment by PROXYhx** [comment]
Hello, I'm having a similar issue here with 2 EFI partitions on the internal SSD. This is probably my issue here but reimaging the drive hasn't helped.

I have Windows installed on an external HDD and I can boot it up just fine using the "volume down + power" boot manager.

However, it fails to boot to Windows when I boot up normally and select Windows using the refind GUI. It ends up with:

"Invalid loader file!
Error: Not found while loading bootmgfw.efi"

Using "sudo efibootmgr -b XXXX -A" also errors out with:

"efibootmgr: Boot entry 3 not found
Could not set active state for Boot0003: No such file or directory"

I don't understand why it thinks that it doesn't exist, but using "efibootmgr" immediately reveals that "Boot entry 3" does in fact, exist.

"efibootmgr" says; "Boot0003* EFI USB Device (WINDOWS DRIVE NAME)"


So it clearly detects my external drive with Windows, and I'm able to manually boot to it using the system boot manager. But using refind hasn't been a choice for me because of this persistent problem.

Any help is greatly appreciated, thanks in advance.

**Comment by imsofresh54** [comment]
> Hello, I'm having a similar issue here with 2 EFI partitions on the internal SSD. This is probably my issue here but reimaging the drive hasn't helped.
> 
> I have Windows installed on an external HDD and I can boot it up just fine using the "volume down + power" boot manager.
> 
> However, it fails to boot to Windows when I boot up normally and select Windows using the refind GUI. It ends up with:
> 
> "Invalid loader file! Error: Not found while loading bootmgfw.efi"
> 
> Using "sudo efibootmgr -b XXXX -A" also errors out with:
> 
> "efibootmgr: Boot entry 3 not found Could not set active state for Boot0003: No such file or directory"
> 
> I don't understand why it thinks that it doesn't exist, but using "efibootmgr" immediately reveals that "Boot entry 3" does in fact, exist.
> 
> "efibootmgr" says; "Boot0003* EFI USB Device (WINDOWS DRIVE NAME)"
> 
> So it clearly detects my external drive with Windows, and I'm able to manually boot to it using the system boot manager. But using refind hasn't been a choice for me because of this persistent problem.
> 
> Any help is greatly appreciated, thanks in advance.

I'll try to help you, since i managed to fix this issue together with @jlobue10 

Can you give me an output of output of lsblk -f

**Comment by rechntz** [comment]
![IMG_20240628_104807](https://github.com/jlobue10/SteamDeck_rEFInd/assets/174037418/957e383f-0703-4aca-86bd-1b0638da6413)
I have similar cases but my windows are on SD CARD, and here's the results with SD CARD Attached

**Comment by tobstargenesis** [comment]
> All fixed, ico path should be first.
> 
> Thank you!

Did you manage to fix the icon issue? 
How?

**Comment by probablyoxy** [comment]
> > All fixed, ico path should be first.
> > Thank you!
> 
> Did you manage to fix the icon issue? How?

you just swap the place of the "volume -----" and "icon -----"
like, in [imsofresh54](https://github.com/imsofresh54)'s image it would instead be

menuentry "Windows" {
     icon /EFI/refind/os_icon2.png
     volume Win_EFI1
     .... etc

its just like html rules, first lines load first, then it moves on and switches locations when it sees "volume", hence why the image doesnt show up because its not located there

p.s. thank you so so much [jlobue10](https://github.com/jlobue10) and [imsofresh54](https://github.com/imsofresh54) you two really made my life a lot easier today <3

**Comment by Bobsmyuncle78** [comment]
I know this is old.  but having the same problem.  kubuntu 23 is gone...so i got kubuntu 22.  command worked and efibootmgr shows my windows as not active.  on reboot to rEFInd same error shows up when attempting to launch windows.
both OS on the same nvme.

also attempted to run the windows side script and it looked like it worked, but same error.

after the command does grub need a command to incorporate the changes?

Thanks and sorry for reviving

**Comment by seanyrocks1** [comment]
Please help me ive just ran into the same issue?
