### ISSUE TITLE
Errors when installing rEFInd.sh

### ISSUE THREAD

**Issue by vpguerrero** [jlobue10/SteamDeck_rEFInd#13]
Upon entering command:
./SteamDeck_rEFInd_install.sh

Output Error Snippet:
refind-0.13.2-1-any.pkg.tar.zst failed to download
error: failed retrieving file 'refind-0.13.2-1-any.pkg.tar.zst' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
sudo: refind-install: command not found

Effect:
Windows Boot Manager is disabled
rEFInd is listed in efibootmgr

Upon restart, OS selection is not loaded, Steam OS will automatically load instead.
Returning to Konsole in Steam Desktop Mode will show that rEFInd is no longer listed in the efibootmgr

Can you please help look into this?

**Comment by jlobue10** [comment]
There seems to be an issue with the Steam Deck's `pacman` repositories. I'm investigating a different installation method that doesn't need `pacman` . I will update the GitHub with an alternate version of the installation script, once I can write it, and test that it works. I'm working on this now.

**Comment by jlobue10** [comment]
Please try the updated refind_install_no_pacman.sh script. README has been updated.

**Comment by vpguerrero** [comment]
Works perfectly! Thank you very much!
