### ISSUE TITLE
Problem with 'cd SteamDeck_rEFInd'

### ISSUE THREAD

**Issue by astnla** [jlobue10/SteamDeck_rEFInd#14]
Hi, I've been working tirelessly to get this dual boot setup. I spent all day trying Deck Wizard's tutorial on YouTube & noticed your strings were a bit different so I wanted to try yours. I'm currently having an issue where the Steam Deck boots into Windows mainly and won't find the rEFInd installation. 

I'm hoping your will, but when I enter the second line that begins with 'cd' it says 'No such file or directory.'

Any help would be amazing, thanks!

EDIT: Never mind, a quick close of the Konsole & reopened allowed me to install but I did see that it had some files that said it couldn't be downloaded. After restarting my Deck, it no longer boots into Windows anymore, it now goes straight to game mode. I'll try reinstalling & pasting the full code here.

**Comment by astnla** [comment]
Never mind, a quick close of the Konsole & reopened allowed me to install but I did see that it had some files that said it couldn't be downloaded. I'll try reinstalling & pasting the full code here.

**Comment by jlobue10** [comment]
You may be experiencing an issue with pacman not installing refind. I literally just uploaded a different install script that addresses this. Please try that and let me know how it goes.

And yes, I've reached out to DeckWizard and let him know that I made multiple script improvements since the initial release. He is either too busy or has ignored my request for him to update his version. This is especially annoying when people use his version, have issues and then come to me for help. It's also comedy seeing some of these fork names with like "improved" attached. It's kind of disrespectful to be honest with the amount of time and effort I've made to ensure this script works and to help others debug, but I digress.

Let me know how the pacman free script works for you, assuming you are also having a problem with pacman getting the refind package for installation.

**Comment by astnla** [comment]
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: key DEB4AEEBFCFCABA9 marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/118CDDB5827CE19511C3558DDEB4AEEBFCFCABA9.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 6 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 53 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   6  signed:  94  trust: 0-, 0q, 0n, 6m, 0f, 0u
gpg: depth: 2  valid:  74  signed:  28  trust: 74-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2023-01-01
resolving dependencies...
looking for conflicting packages...

Packages (1) refind-0.13.2-1

Total Download Size:   3.45 MiB
Total Installed Size:  5.01 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 **refind-0.13.2-1-any.pkg.tar.zst failed to download
error: failed retrieving file 'refind-0.13.2-1-any.pkg.tar.zst' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
warning: failed to retrieve some files**
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
sudo: refind-install: command not found
BootCurrent: 0004
Timeout: 0 seconds
BootOrder: 0005,0004,2001,2002,2003
Boot0000* EFI PXE 0 for IPv4 (00-E0-4C-68-09-77) 
Boot0001* EFI PXE 0 for IPv6 (00-E0-4C-68-09-77) 
Boot0002* EFI USB Device (TOSHIBA EXTERNAL_USB)
Boot0004* SteamOS
Boot0005  Windows Boot Manager
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
Boot0005  Windows Boot Manager
BootCurrent: 0004
Timeout: 0 seconds
BootOrder: 0005,0004,2001,2002,2003
Boot0000* EFI PXE 0 for IPv4 (00-E0-4C-68-09-77) 
Boot0001* EFI PXE 0 for IPv6 (00-E0-4C-68-09-77) 
Boot0002* EFI USB Device (TOSHIBA EXTERNAL_USB)
Boot0004* SteamOS
Boot0005  Windows Boot Manager
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
Invalid bootnum value: FFFFFFFFFFFFFFF5

BootCurrent: 0004
Timeout: 0 seconds
BootOrder: 0005,0004,2001,2002,2003
Boot0000* EFI PXE 0 for IPv4 (00-E0-4C-68-09-77) 
Boot0001* EFI PXE 0 for IPv6 (00-E0-4C-68-09-77) 
Boot0002* EFI USB Device (TOSHIBA EXTERNAL_USB)
Boot0004* SteamOS
Boot0005  Windows Boot Manager
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
cp: cannot stat '/boot/efi/EFI/refind/': No such file or directory
BootCurrent: 0004
Timeout: 0 seconds
BootOrder: 0003,0005,0004,2001,2002,2003
Boot0000* EFI PXE 0 for IPv4 (00-E0-4C-68-09-77) 
Boot0001* EFI PXE 0 for IPv6 (00-E0-4C-68-09-77) 
Boot0002* EFI USB Device (TOSHIBA EXTERNAL_USB)
Boot0004* SteamOS
Boot0005  Windows Boot Manager
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
Boot0003* rEFInd
rEFInd has now been installed.

**Comment by astnla** [comment]
Alright, let me go ahead and try that! :)

**Comment by astnla** [comment]
IT WORKED!! Thank you so much! I've been trying numerous amounts of guides online that say they fix it but don't! Thank you for helping, seriously! I spent all day yesterday trying to get this to work! I appreciate it!!

**Comment by jlobue10** [comment]
Let's go! I'm happy that it worked. Thank you for confirming that this worked for you. If you're happy with the resolution, please close the issue.

**Comment by astnla** [comment]
Yes, I will! I think you should make your own tutorial on YouTube, honestly! If you search this issue, a lot of people have it. I think you should make your own! This helped out a ton, seriously. Thank you!

**Comment by jlobue10** [comment]
Thank you for the positive feedback. Unfortunately I am far too busy with a full time job and daddy duties with a baby. I also don't care about internet clout or whatever... XD . Hopefully people stumble upon the fix, if nothing else. I updated the main Reddit thread to mention it [here](https://www.reddit.com/r/SteamDeck/comments/xhvhsd/installation_script_for_refind_boot_manager_when/) . Have a nice day. :)
