### ISSUE TITLE
Dual Boot Screen not showing up

### ISSUE THREAD

**Issue by ashejinn** [jlobue10/SteamDeck_rEFInd#15]
Hello, thank you so much for working on this. It seems like a really cool feature but I'm having trouble making it work properly.

I've made sure that Steam and Windows boot entries are at the exact location you have mentioned. I am running Steam on the stable branch and Windows 10. Followed the instructions exactly but when I boot up my deck, it automatically boots into SteamOS without showing the option to choose between Steam and Windows. I've reinstalled a few times just to make sure but no luck.

I understand you are busy with your personal life so feel free to take your time when looking at this. I appreciate any and all help :) Please let me know if I need to provide any additional information. Thank you!

From latest install:
(deck@steamdeck SteamDeck_rEFInd)$ ./SteamDeck_rEFInd_install.sh
deck P 12/21/2022 0 99999 7 -1
Password is already set.
[sudo] password for deck: 
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: key E691D6D086CD60AA marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/ACFCFD358A579E424A06C47AE691D6D086CD60AA.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 6 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 53 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   6  signed:  94  trust: 0-, 0q, 0n, 6m, 0f, 0u
gpg: depth: 2  valid:  74  signed:  28  trust: 74-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2023-01-01
resolving dependencies...
looking for conflicting packages...

Packages (1) refind-0.13.2-1

Total Download Size:   3.45 MiB
Total Installed Size:  5.01 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 refind-0.13.2-1-any.pkg.tar.zst failed to download
error: failed retrieving file 'refind-0.13.2-1-any.pkg.tar.zst' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
sudo: refind-install: command not found
BootCurrent: 0003
Timeout: 0 seconds
BootOrder: 0002,0003,2001,2002,2003
Boot0002* Windows Boot Manager
Boot0003* SteamOS
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
Boot0002* Windows Boot Manager
BootCurrent: 0003
Timeout: 0 seconds
BootOrder: 0002,0003,2001,2002,2003
Boot0002  Windows Boot Manager
Boot0003* SteamOS
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
Invalid bootnum value: FFFFFFFFFFFFFFF5

BootCurrent: 0003
Timeout: 0 seconds
BootOrder: 0002,0003,2001,2002,2003
Boot0002  Windows Boot Manager
Boot0003* SteamOS
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
cp: cannot stat '/boot/efi/EFI/refind/': No such file or directory
BootCurrent: 0003
Timeout: 0 seconds
BootOrder: 0000,0002,0003,2001,2002,2003
Boot0002  Windows Boot Manager
Boot0003* SteamOS
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
Boot0000* rEFInd
rEFInd has now been installed.
(deck@steamdeck SteamDeck_rEFInd)$

**Comment by jlobue10** [comment]
You will need to use the newly added `refind_install_no_pacman.sh` script instead, since the `pacman` repositories seem to be having issues for some users. The README has been updated (at the bottom). Basically re-clone this repository and run the no pacman script version. Please let me know if it works for you. Multiple users have already reported success with it. Thanks.

**Comment by ashejinn** [comment]
That did wonders! Tysm!!
