### ISSUE TITLE
[not  issue] Just wanted to report that SteamOS 3.4 worked fine for me

### ISSUE THREAD

**Issue by Kazlehoff** [jlobue10/SteamDeck_rEFInd#16]
Hi, going to open and close this right away, so the dev can see. 

I'm using rEFInd and updated to 3.4. There was no issue with the update. rEFInd worked fine immediately on boot with no special consideration.

**Comment by jlobue10** [comment]
Thanks for this. It seems that mileage may vary. I will be experimenting the next few days. I'm glad it went smoothly for you.
