### ISSUE TITLE
Black screen on boot when Docked

### ISSUE THREAD

**Issue by Kazlehoff** [jlobue10/SteamDeck_rEFInd#21]
Hey!

I dont get any video output when i boot my deck while docked. 

Im using the JSAUX HB0602. I've updated the firmware to the latest version.

dock is connected to a Viotek GNV30CB (2160x1080. Monitor supports 144hz, dock is connected via HDMI 1.4, so 75Hz)

When i boot, i get no video out from the dock, or the deck.

I just want to check if this is a dock issue, and if theres a way to check, or a rEFInd issue. At this point, im not pointing fingers, just trying to sort out the potential issue.

**Comment by jlobue10** [comment]
It is most likely an issue with your dock or cable connecting the dock and monitor. I also have a JSAUX dock and find the HDMI port finnicky, working sometimes to show the rEFInd screen and other times not. I'd say if you have the monitor working in the OS, see if rEFInd will display properly when you perform a restart. If it works okay on restart, I think you have your answer (dock or connection issue).

**Comment by Kazlehoff** [comment]
IS there a way to define in the conf file the default boot display, to have the boot menu show up on the dock regardless of a connected display?

**Comment by jlobue10** [comment]
Unfortunately, I don't think there's a way to change this in the config file. I don't see an applicable option [here](https://www.rodsbooks.com/refind/configfile.html). I know it's annoying, but best bet is to probably just unplug the external display on boot temporarily.

**Comment by johnrkriter** [comment]
@Kazlehoff 
I am using the JSAUX dock and found that if I increase the timeout to about 15 seconds, the menu has enough time to show up on the external. I suspect this is happening because of a display port mode shift when you pass from BIOS into a deployed OS.

**Comment by jlobue10** [comment]
This is not directly related to the code provided in this repo. Either fix it with a higher refind timeout value, or discover and fix any potential hardware or cable issue. Closing...
