### ISSUE TITLE
SteamOS update overrides rEFInd boot

### ISSUE THREAD

**Issue by jlobue10** [jlobue10/SteamDeck_rEFInd#3]
After the latest SteamOS update this morning, I found that rEFInd was not popping up for me on reboot or a fresh power on. It seems that something is being overwritten. The fix was simple enough though. Just re-run the installation script from the SteamOS desktop mode command line. This is safe to do consecutive times now as of v1.0.2 (without any intermediate command line steps), as the script will remove one duplicate rEFInd EFI boot entry (assumed from previous script run).

**Comment by thitoro** [comment]
How do I uninstall the rEFInd in Steam Deck?

**Comment by jlobue10** [comment]
Your uninstall question was answered in a separate issue @thitoro .

I may need to look into potential `bcdedit` workarounds from the Windows side for modifying EFI boot entries, since SteamOS beta and newer versions seem to keep breaking `efibootmgr` proper functionality. This issue will remain open until I can investigate those other potential workarounds (and situational needs).

**Comment by jlobue10** [comment]
Closing this as it's similar to the 3.4 issues. Multiple fixes and workarounds exist.
