### ISSUE TITLE
Dual Boot Crashes The Deck When I Launch Win11

### ISSUE THREAD

**Issue by Benjiiiiiiiiiii** [jlobue10/SteamDeck_rEFInd#40]
Whenever I try to launch windows a bunch of blue lines appear, and nothing happens after that.

**Comment by jlobue10** [comment]
Is this supposed to be enough information for me to help you trouble shoot with?

With that being said, are you trying to boot from Windows from the internal NVMe, SD card or external drive on USB? Did you successfully install Windows previously?  Did it boot okay before? This is minimal information for me to try to help you.

**Comment by Benjiiiiiiiiiii** [comment]
It’s booting from an internal NVME. Windows runs perfectly with all drivers when I use boot manager. It never worked for me I just tried it today

**Comment by jlobue10** [comment]
Can you provide a screenshot of what you are talking about, both your rEFInd boot screen and the blue lines screen? Did you have any issues completing the installation? Did you perform the create config and install config steps from the GUI?

**Comment by Benjiiiiiiiiiii** [comment]
Sure I’ll provide both of when I get home. Also can a modded rufus iso be the problem (Removed Windows 11 Requirements)

**Comment by jlobue10** [comment]
A modded Rufus iso shouldn't be a problem, I would think (firmware TPM is supported by Steam Deck though by the way). The way my config for the bootloader functions is by pointing to the Windows EFI file to launch. If that EFI file is not there on the `/esp` partition for some reason, that could be a problem (but solvable with some Windows command prompt commands). Are you able to boot from the Windows EFI file (Vol Up and Power, bottom left option)?

Are you perhaps using BitLocker on the Windows partition? Some other user claimed pointing to the EFI file does not work in that case. I haven't had a chance to double check and test that though.

**Comment by Benjiiiiiiiiiii** [comment]
I’ll just try again and if the issue persists I’ll send the pictures.

**Comment by Benjiiiiiiiiiii** [comment]
Sorry that was an accident

**Comment by Benjiiiiiiiiiii** [comment]
![C1CB4CB2-8ADC-4829-8CA9-CA0A1053798C](https://user-images.githubusercontent.com/97795842/219960507-2e4a3509-e74b-43de-be23-8215a9e25bc0.jpeg)
![2E1C9819-F659-48D1-BBF6-791653C96688](https://user-images.githubusercontent.com/97795842/219960510-8dad1c4c-6151-4c8a-8044-15935de1f6ab.jpeg)
![248A2780-002E-49A5-9CEC-05832E76A2F2](https://user-images.githubusercontent.com/97795842/219960512-78b3d7f8-e8b2-4deb-bcb4-65599fb9bf71.jpeg)

it still doesn’t work and BitLocker is disabled

**Comment by Benjiiiiiiiiiii** [comment]
It’s in the esp partition and boots normally when I hold vol+

**Comment by jlobue10** [comment]
Ok. Boot into Windows and make sure that the APU driver is installed and  up to date.

Refer to this portion of the [README](https://github.com/jlobue10/SteamDeck_rEFInd#additional-windows-considerations-corrupted-display-on-boot-into-windows). Run that command from either command prompt or Powershell, and then try again.

**Comment by Benjiiiiiiiiiii** [comment]
OMG thank you so much. The issue is fixed. Really appreciate it brother.
