### ISSUE TITLE
Windows SD won't boot (no EFI partition on sd card?)

### ISSUE THREAD

**Issue by Staubgeborener** [jlobue10/SteamDeck_rEFInd#43]
So i have SteamOS on NVMe and Windows 10 on sd card. KDE Partition Manager shows me two partitions from the sd card:
```
ntfs     ESD-ISO     119.08 GiB
fat12    UEFI_NTFS     1.00 MiB
```

Both partition **don't** have a "EFI System partition" partition label. But i can boot from sd card normally from the bios. The UUID format of both partitions also looks a little bit weird:
```
ntfs     UUID: 2984657982374983D
fat12    UUID: AB12-1B2A
```

(both UUIDs are thought up, it's only about the format).

I edited the `refind.conf` like this at the end:
```
menuentry "Windows SD card" {
    icon /EFI/refind/icons/os_win11.png
    volume 2984657982374983D
    loader /EFI/Microsoft/Boot/bootmgfw.efi
    graphics on
}
```

I also tried this later
```
menuentry "Windows SD card" {
    icon /EFI/refind/icons/os_win11.png
    volume AB12-1B2A
    loader /EFI/Microsoft/Boot/bootmgfw.efi
    graphics on
}
``` 

In Steam Deck rEFInd i added this:
```
Boot Option #1: SteamOS
Boot Option #2: Windows (SD)
```

After booting the Steam Deck i can choose between SteamOS and Windows. SteamOS boots properly, but the Windows icon does nothing.

**Comment by jlobue10** [comment]
The `fat32` partition should be the correct one for the EFI file. You need the partition UUID for the volume, not the normal UUID. They are different. The GUI handles this automatically when you perform the create config step as long as you choose Windows (SD), as long as the SD card is plugged in and is valid. Make sure to install the config after the create config step. I'd suggest trying the GUI and let me know how it goes for you.

**Comment by jlobue10** [comment]
Also, what method did you use to create the Windows to Go for your SD card? Did you use Rufus? Did you ensure that it was using GPT partition scheme?

**Comment by Staubgeborener** [comment]
step by step what i did:

1. Open KDE partition manager > right click on fat32 sd card partiton -> copied UUID (`AB12-1B2A`).
2. Edit `refind.conf` like this
```
menuentry "Windows SD card" {
    icon /EFI/refind/icons/os_win11.png
    volume AB12-1B2A
    loader /EFI/Microsoft/Boot/bootmgfw.efi
    graphics on
}
```

3. open rEFInd GUI, change this
```
Boot Option #1: SteamOS
Boot Option #2: Windows (SD)
```

4. click `Install rEFInd`
5. click `Create Config`
6. click `Install Config`
7. Restart Steam Deck, recognize issue while trying to boot windows from sd card


Yes, i always use rufus, but I can't tell you if i used GPT partiton scheme.

**Comment by jlobue10** [comment]
Thank you for the more detailed info. Yes, that partition volume label seems much too short. I suspect that MBR may have been set when you created the SD card Windows to Go. Would you mind rebuilding your Windows to Go on the SD card with Rufus and ensure that GPT partition scheme is used? I think this very well may be your issue. It's nearly bed time for me here too, so I may not respond for a bit after this. Thanks.

**Comment by Staubgeborener** [comment]
I checked the sd card via `disk managament` (right click -> properties). Indeed, looks like MBR. I will rebuild everything and give you an update. Good night.

**Comment by jlobue10** [comment]
Okay. Sounds great! Sounds like my suspicions were on point. Yes, it needs to be GPT. Fix that and redo the steps and you should be good to go.

**Comment by Staubgeborener** [comment]
Ok, so first: Rebuilding the sd card with GPT is working. The UUID is now definitely longer like in the readme file. 

![grafik](https://user-images.githubusercontent.com/28908603/221823993-99e89444-6031-4212-80f9-f92597d4a871.png)


But now there is another issue. The `Windows Boot Manager` is now at first position, so every time windows will be booted instead rEFInd.
![grafik](https://user-images.githubusercontent.com/28908603/221825031-ae8173a8-1164-4a07-b2d0-6def259f5bb8.png)

I also tried to disable and delete this entry with `efibootmgr`. This worked for some minutes, but i think windows itself re-create this entry at the first position everytime?
Like `sudo efibootmgr -b 0004 -B` (0004 = `Windows Boot Manager` entry). I re-checked it and yeah, after booting windows and looking into `efibootmgr` this entry is back there. Any chance to disable this with `SteamDeck_rEFInd`?

**Comment by jlobue10** [comment]
Yeah, there are some strange quirks with the Steam Deck firmware. Boot order is not respected if you try to force it with `sudo efibootmgr -o`, but there's a clever way to reset it in a way that is respected. What I do if something else has hijacked into a higher boot order priority than rEFInd and/ or SteamOS is boot into SteamOS manually, and delete both the SteamOS and rEFInd EFI entries with `sudo efibootmgr -b XXXX -B (replace numbers into XXXX accordingly). Then I run the provided `restore_EFI_entries.sh` script. Since rEFInd entry is added back last with that script, it will be first in the new boot order. Also, it's pretty common to need to disable the Windows EFI entry with `sudo efibootmgr -b XXXX -A`, not delete it. The firmware will readd the entry if you try to delete it, so this is ineffective. You will need to boot into the SteamOS recovery USB to do this from the SteamOS side, or you can use EasyUEFI on the Windows side.

Hopefully this is enough info to get you on the right track to a solution for your use case. I haven't tested too much for Windows on Micro SD, other than to ensure my code grabs the `volume` info appropriately and can boot into it. I did have Ventoy on the SD card hijack the boot order this morning (pushing the Micro SD card as highest in priority), but I fixed this with my described method using the provided script.

**Comment by jlobue10** [comment]
I also had to disable the SD card EFI entry (0003 for me) this morning, as some similar boot order hijacking was happening for me this morning with Ventoy. You may need to do the same. This is new to me, as far as potentially needing to do this.

**Comment by Staubgeborener** [comment]
Sounds good, but disabling boot entries don't work on my side.
`sudo efibootmgr` shows me `Boot0004* Windows Boot Manager`. Running `sudo efibootmgr -b 0004 -A`  (or `sudo efibootmgr -b 4 -A`) leads to 
```
efibootmgr: Boot entry 4 not found
Could not set active state for Boot0004: No such file or directory
```
and yeah, this is pretty weird.

**Comment by jlobue10** [comment]
You have to do this from the SteamOS recovery image or another Live Linux USB. This has been a bug with `efibootmgr` with SteamOS 3.4+, where disabling entries no longer works. It worked in older versions of SteamOS, prior to 3.4.

**Comment by Staubgeborener** [comment]
I booted the latest recovery image and did these steps:

1. `sudo efibootmgr -b SteamOS-ID,rEFInd.ID -B`
2. mount nvme to access `SteamDeck_rEFInd` files: `sudo mount /dev/nvme0n1p8 /mnt`
3. `cd /mnt/deck/SteamDeck_rEFInd && chmod +x restore_EFI_entries.sh && ./restore_EFI_entries.sh`
4. `sudo efibootmgr -b WindowsEFI-ID -A`
5. check everything with a simple `sudo efibootmgr`

So far it seems to work and no matter which OS i booted last, every time `SteamDeck_rEFInd` will be booted as the first entry. All in all i will close this issue, thanks for the help.


Oh, and maybe you want to add this GPT scheme part in your `readme.md`?
