### ISSUE TITLE
Windows 11 reinstallation 

### ISSUE THREAD

**Issue by Ghardir11** [jlobue10/SteamDeck_rEFInd#47]
Hello I used you scripts to installation of Windows 11 everything went Good and Windows worked. But i get some problems after several days so I decided to reinstall. I just booted USB pendrive with Windows next formatted partition and installed Windows again. When instalation done and system rebooted i have no screen just any lines on black background and Windows no load. Steam load perfect. Windows no.  Where is the problem? What is reinstallation tutorial ?

**Comment by jlobue10** [comment]
Can you provide a screenshot of the error that you are talking about? I think I know what's going on, but a screenshot will give more me information.

**Comment by Ghardir11** [comment]
![81F67894-4E4C-4EB4-A0CA-3473DF89BBD0](https://user-images.githubusercontent.com/127780027/224791162-6ee29316-54f8-480a-9f57-c44d6436e8ff.jpeg)

**Comment by Ghardir11** [comment]
The dual boot screen with steam icon and Windows working but when i choose Windows i have this

**Comment by Ghardir11** [comment]
![B551AC4D-9976-4474-834A-A65BB1D801EC](https://user-images.githubusercontent.com/127780027/224796102-8b7221e5-46b3-4ab8-930f-2719dc57b1ea.jpeg) there no Windows but is installed

**Comment by jlobue10** [comment]
That's the wrong menu. Boot from file is the bottom left option from BIOS. You are looking at EFI entries, not the actual EFI files

**Comment by Ghardir11** [comment]
![1AB84A73-82AA-4C38-858D-FD3C7133D27A](https://user-images.githubusercontent.com/127780027/224798421-f54f83fc-ad35-4744-aa92-ce8223c87c76.jpeg) which one ?

**Comment by jlobue10** [comment]
Top one. You have to navigate to `/esp/efi/Microsoft/Boot/bootmgfw.efi` and select that efi file to launch.

**Comment by Ghardir11** [comment]
![48EC3B13-6984-4DE9-8B93-ECB5985B2E4F](https://user-images.githubusercontent.com/127780027/224800017-5d46bcb3-3655-48c5-a92e-df25399d638f.jpeg)
I have there 2 Windows both not working. Info installation not complete

**Comment by Ghardir11** [comment]
![AC221677-0871-48E8-B2CF-BB38E2F9F847](https://user-images.githubusercontent.com/127780027/224800223-5f91ae76-5e4f-4a1d-868b-164c57fa7371.jpeg)

**Comment by jlobue10** [comment]
Are you following the instructions from [here](https://github.com/jlobue10/SteamDeck_rEFInd#necessary-steps-for-reinstalling-windows)? It seems the Windows reinstallation did not finish. I recommend disabling rEFInd until Windows reinstallation is finished.

If I were in your situation, I'd probably just delete those Windows partitions after the `/dev/nvme0n1p8` `/home` partition and start with a fresh reinstallation with rEFInd disabled. You will also either want to delete the Windows EFI entry or make sure that the existing one is active for reinstallation. I'd probably just delete it though as reinstallation should re-add it properly.

**Comment by Ghardir11** [comment]
I removed partition atm and make again. How to disable this refind and How to remove old Windows entries?

**Comment by jlobue10** [comment]
From SteamOS, go to desktop mode and please tell me the output of `efibootmgr` from a command line. This will help me to tell you exactly what commands to run.

**Comment by Ghardir11** [comment]
![95BE41E6-1A42-45EE-B7E7-7751791A4829](https://user-images.githubusercontent.com/127780027/224810554-0646f93f-656a-4ddc-9ab5-3d36da540b10.jpeg)
This is after removed Windows partition

**Comment by jlobue10** [comment]
Can you please run the GUI and click the `Sysd Off` button? You will need the latest version of the GUI. Then I'd also just run these two commands.

```
sudo efibootmgr -b 0000 -B
sudo efibootmgr -b 0004 -B
```
These commands should delete the EFI entries for both rEFInd and Windows. Please show me the output of `efibootmgr` afterwards.

**Comment by Ghardir11** [comment]
This one ?
![7EE56266-57C6-4319-998C-478177D442E2](https://user-images.githubusercontent.com/127780027/224815736-0dd8747b-6f51-4ebc-aa3a-773906a04f6e.jpeg)

**Comment by jlobue10** [comment]
Yes. I want to make sure that the rEFInd EFI entry is not re-created automatically on boot until your configuration is fixed. This Sysd Off button will accomplish that. It opens an xterm to run the necessary commands and will require the `sudo` password.

**Comment by Ghardir11** [comment]
![9BDD953F-5A0E-4ADA-9343-63516AB59313](https://user-images.githubusercontent.com/127780027/224819507-3d90c6b1-eca9-4abe-a69d-1697d31db9d4.jpeg)
![02E9564B-08CB-4D0F-8707-2899661B50AC](https://user-images.githubusercontent.com/127780027/224819535-32c2e6ff-b1dd-46c3-a9d4-13eafd65a8cf.jpeg)

**Comment by jlobue10** [comment]
Looks good. You should be good to restart the Windows reinstallation process now.

**Comment by Ghardir11** [comment]
Still installation not complete because when Windows instalation finished and device rebooted this loaded steam os

**Comment by jlobue10** [comment]
Can you show me the output of `efibootmgr` now? It's possible that the deactivated Windows EFI entry wasn't actually deleted.

**Comment by Ghardir11** [comment]
Now i booted from file and Windows loaded. But i have on blue screen 3 entries How to remove it? And How to start refind now to get dual boot screen

**Comment by jlobue10** [comment]
This [video](https://youtu.be/CpDi2ogQsXo) describes fixing the multiple entries. As for reinstalling rEFInd, please consult the GUI readme. From the steps we've done, I'd re-enable the `systemd` service (Sysd On) and make sure config is proper and installed. It's probably best to disable the Windows EFI entry again, if it's not already disabled from previous steps.

**Comment by Ghardir11** [comment]
I dont know why cant add Windows efi 
![821D1AD0-2D3F-4BCD-85EE-DF1D265C64E0](https://user-images.githubusercontent.com/127780027/224843057-5bfe3d2c-9446-4690-a774-694f8acf8fc2.jpeg)

**Comment by Ghardir11** [comment]
When I put this command sudo efibootmgr -b 0004 -a

now i have just Windows load. I dont have dual boot icons just Windows loading automatically. What to do now ?

**Comment by Ghardir11** [comment]
how to make refind start after booting the device?

**Comment by jlobue10** [comment]
SO you were able to finish the Windows reinstallation now? That was the point of re-enabling the Windows EFI entry. Can you boot into SteamOS recovery USB and tell me the output of `efibootmgr`? If everything is setup properly again, the last step would be to disable the Windows EFI entry so that rEFInd can assume the top boot priority.

**Comment by Ghardir11** [comment]
I have finished Windows installation now i just need dual boot screen because now Windows loading automatically and cant choose steam os

**Comment by jlobue10** [comment]
Can you boot into SteamOS recovery USB and tell me the output of efibootmgr? If everything is setup properly again, the last step would be to disable the Windows EFI entry so that rEFInd can assume the top boot priority.

Providing me with this info will help me to help you.

**Comment by Ghardir11** [comment]
![E035AC27-A8CB-4FCA-988C-C16D43093F5C](https://user-images.githubusercontent.com/127780027/225045297-6f179f06-65c0-4eb2-b019-70823317d786.jpeg)

**Comment by Ghardir11** [comment]
Thank you now All working good

**Comment by jlobue10** [comment]
Happy to help. Closing the issue.
