### ISSUE TITLE
Unable to Schedule Task

### ISSUE THREAD

**Issue by StormWolf49** [jlobue10/SteamDeck_rEFInd#48]
I was following along with the instuctions of the README to setup up the schedueled task to prioritize rEFInd in the boot order from the windows side, and I ran into a problem that prevented me from editing the properties of the task I created.
![image](https://user-images.githubusercontent.com/72424123/226454565-ab19726d-f9f9-4ec8-9b96-b7623bfad7f4.png)
This is the error I keep getting, and I'm not sure what might be the reason. For context I've already got rEFInd installed and have disabled the Windows EFI.

**Comment by jlobue10** [comment]
I'm assuming that this is a typo or other user error. Closing the issue.
