### ISSUE TITLE
Considerations for reinstalling SteamOS on a dual boot Steam Deck

### ISSUE THREAD

**Issue by jlobue10** [jlobue10/SteamDeck_rEFInd#49]
This issue is being created for documentation and reference purposes (placed here in order to not clobber the main README).

If, for whatever reason, you feel the need to reinstall SteamOS on a functioning dual boot Steam Deck, there are some extra considerations and issues that you may encounter. Some common reasons for needing to reinstall SteamOS are software package or `pacman` configuration corruption (that can't be easily remedied), or some other system or partition error. If you feel this is happening on your Steam Deck and programs are either acting weird or not working at all, then the reinstall SteamOS from the SteamOS recovery USB may be the option that you're looking for. Reimage should be the last resort, and will delete the full drive before reimaging.

The reinstall option will redo the first 7 partitions, and the `/home` (8th partition) and subsequent partitions like your Windows installation (for instance) will not be touched. The problem is though, that the EFI boot loader files for Windows and any other Linux or other operating system will be wiped when the `/esp` partition is recreated. After a successful reinstallation of SteamOS, make sure to update immediately to the latest SteamOS upon first boot. This is to prevent software issues that may happen from running an older version of SteamOS. Programs like Decky Loader, CryoUtilities, and this rEFInd GUI will need to be reinstalled as well.

To restore the Windows EFI files and EFI entry properly, you will need the Windows installation USB to get to a command prompt. Boot off of the Windows installation USB and choose 'Repair your computer' when that option shows up. Use the buttons to get to a troubleshooting command prompt. From there, you will need to use a series of `diskpart` commands to prepare the proper volumes for the `bcdboot` command. It will look something like this.

![diskpart_example](https://user-images.githubusercontent.com/9971433/226782481-3fe30d49-41d2-40a4-9922-add7c2734e3f.png)

In this example screenshot, I would have to run these commands to get the `/esp` partition mounted in preparation for the `bcdboot` command.

```
diskpart
list vol
sel vol 4
assign letter=H
exit
cd C:\Windows\System32
bcdboot C:\Windows /s H:
```
The important things to note here is that my Windows partition is mounted as the `C` drive and the `/esp` partition is mounted as the `H` drive (in my example). If all went properly, the EFI files should be restored on the `/esp` partition and the Windows EFI entry would have been recreated (remember to disable again!!).

For Linux or other OS EFI files, I'd probably just recommend reinstalling, and I won't go into much detail about that since it's a much rarer use case that I can support as necessary (if people open issues, or respond here).

**Comment by Modelero** [comment]
Hi, i had to reinstall SteamOS (it was stuck in a "rebooting into firmware" loop), the operation went well and I didn't loose any personal data, then I lost the option to boot into windows and I restored it by following your guide here.
Now I'm able to manually boot in SteamOS or Win10 without any problem, but I can't manage to get rEFInd working again.
Since I didn't loose any data when I reinstalled SteamOS, I still had my rEFInd folders and data, I've opened the setup installer and went on with the regular install procedure (install refind, create config and install config) but the dual boot screen still won't show up on startup.
Is it normal? am i supposed to remove rEFInd and install it fresh to get it back to working again?
Thanks.

**Comment by jlobue10** [comment]
Please show me the output of `efibootmgr` and the contents of your `refind.conf` file (on the `/esp` partition).

**Comment by Modelero** [comment]
![Image](https://github.com/user-attachments/assets/2abb4eee-0815-43bb-a45f-9e2ddbe51ac6)

![Image](https://github.com/user-attachments/assets/6071327b-fc81-4c8a-bcad-5b181a0a9415)

**Comment by Modelero** [comment]
Another weird thing is that whenever i start SteamOS after using Windows, I need to follow the setup procedure, as if I reinstalled SteamOS again (select language, time zone, all the main settings get reset but the data is still there)
