### ISSUE TITLE
conf changes post install

### ISSUE THREAD

**Issue by aqsede** [jlobue10/SteamDeck_rEFInd#5]
Hi, 

Do we need to rerun the script again after making change to the config file or just reboot and it will work automatically? 

Thanks.

**Comment by jlobue10** [comment]
There is no need to rerun the script after making changes to the `refind.conf` file. I do this often to test or use different backgrounds and icons. The script is mainly just to automate copying the files to the correct location and fix the EFI boot entries.

**Comment by aqsede** [comment]
Thank you. I edited the wrong conf and didn't get the notification when you edit your comment so I was stuck till just now. Thank you
