### ISSUE TITLE
add Check for Updates button GUI app

### ISSUE THREAD

**Issue by dtantono** [jlobue10/SteamDeck_rEFInd#50]
Hi
CryoUtilities have check for update button to simplify gamers/users/Linux noobs to ensure the GUI version on latest version and I hope this app have same feature. What do you think?

**Comment by jlobue10** [comment]
This is definitely a good idea. I'll try to get to it at some point, but it is somewhat of a low priority and I don't expect too many changes to the GUI at this point. The GUI already does everything that I set out for it to do in the brainstorm phase. Bug fixes or changes that may be required from SteamOS updates will definitely still occur in the future, as necessary.

**Comment by jlobue10** [comment]
Added with version 1.1.9 to the 'About' box.
