### ISSUE TITLE
Go back to Steam OS only (remove windows 11 and rEFInd)

### ISSUE THREAD

**Issue by imdavid555** [jlobue10/SteamDeck_rEFInd#54]
Steam OS has been working really well for me, that I don’t want Windows anymore.
So I would like to remove Windows 11 and rEFInd from my Steam Deck. This is all installed on the internal drive.

Any instructions on how to undo windows 11 and rEFInd, then reclaim that hard drive space to steam OS?

**Comment by jlobue10** [comment]
The quickest way with the simplest steps would be to boot into the SteamOS recovery image, delete the Windows partition(s) with KDE Partition manager or GParted, remove the rEFInd and Windows EFI entries with applicable `efibootmgr` commands, and then run the reinstall SteamOS option (not Re-image!). Upon reboot after that, SteamOS should reclaim that empty space at the end of the drive for the `/home` partition. If this does not happen automatically, just use KDE partition manager or GParted to reclaim that space for `/home`.

**Comment by jlobue10** [comment]
There is abundant information and documentation online. Use that in combination with my guidance above. Closing issue.

**Comment by imdavid555** [comment]
Thank you very much for the guidance.
I apologize if this was asked before but I could not find with a google search easily anything clear instructions except a few Reddit threads saying to just reimage or just removing rEFInd (and not windows).

This worked and I am all set. Thanks again!
