### ISSUE TITLE
No Linux entry for systemd-boot installation in GUI

### ISSUE THREAD

**Issue by FearlessSpiff** [jlobue10/SteamDeck_rEFInd#57]
Hi.
As discussed on [reddit](https://www.reddit.com/r/SteamDeck/comments/xhvhsd/installation_script_for_refind_boot_manager_when/):
I installed arch-linux using the XBOOTLDR method described [here](https://wiki.archlinux.org/title/systemd-boot#Installation_using_XBOOTLDR) to get around the problem of the small ESP partition on the deck. Now I am missing an entry to generate the correct config on the ui. The systemd-bootloader is located here: `/EFI/systemd/systemd-bootx64.efi`
Thanks!

**Comment by jlobue10** [comment]
Could you re-clone, re-compile and try now? The baby napped long enough for me to make these simple changes in Qt Creator. Let me know how it goes, and I can do the more complete version update and release later if all is good. Thanks!

**Comment by FearlessSpiff** [comment]
Sorry. Took me some time. Just recompiled, and successfully tested the changes. Works great. Thanks!
