### ISSUE TITLE
qmake fails with Project ERROR: Cannot run compiler 'g++'. Output:

### ISSUE THREAD

**Issue by WojtekHenszke** [jlobue10/SteamDeck_rEFInd#59]
Hey,
It looks like, for some reason, `qmake` stage of `install-GUI.sh` is failing:

```
Packages (5) glibc-2.36-6  hwinfo-22.1-1  lib32-glibc-2.36-6  linux-api-headers-5.18.15-1  qt5-base-5.15.6+kde+r180-1

Total Installed Size:  137.16 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] 
(5/5) checking keys in keyring                                                             [####################################################] 100%
(5/5) checking package integrity                                                           [####################################################] 100%
(5/5) loading package files                                                                [####################################################] 100%
(5/5) checking for file conflicts                                                          [####################################################] 100%
(5/5) checking available disk space                                                        [####################################################] 100%
:: Processing package changes...
(1/5) reinstalling linux-api-headers                                                       [####################################################] 100%
(2/5) reinstalling glibc                                                                   [####################################################] 100%
warning: directory permissions differ on /var/db/
filesystem: 711  package: 755
Generating locales...
  en_US.UTF-8... done
Generation complete.
(3/5) reinstalling lib32-glibc                                                             [####################################################] 100%
(4/5) reinstalling hwinfo                                                                  [####################################################] 100%
(5/5) reinstalling qt5-base                                                                [####################################################] 100%
:: Running post-transaction hooks...
(1/4) Reloading system manager configuration...
(2/4) Creating temporary files...
/usr/lib/tmpfiles.d/steamos.conf:24: Duplicate line for path "/var/empty", ignoring.
/usr/lib/tmpfiles.d/tmp.conf:12: Duplicate line for path "/var/tmp", ignoring.
/usr/lib/tmpfiles.d/var.conf:19: Duplicate line for path "/var/cache", ignoring.
(3/4) Arming ConditionNeedsUpdate...
(4/4) Updating the info directory file...
`Project ERROR: Cannot run compiler 'g++'. Output:`
===================
===================
Maybe you forgot to setup the environment?
make: *** No targets specified and no makefile found.  Stop.

GUI compile failed. Please try again after ensuring that your cloned repo is up to date and your pacman config is normal.
```

Tried to additionally install `sudo pacman -Sy base-devel` but still no luck :(
Any help?

**Comment by jlobue10** [comment]
Yes, I've seen compile errors before from other users, but I've never been able to replicate the errors in my own testing. My solution is for those who experience these compile errors to download the `rEFInd_GUI.tar.gz` tarball and extract the whole directory to `/home/deck`. In the even rarer case(s), the compiled version with static C libraries is provided. Again, I have not ever been able to replicate why some people need this static C library version and others do not (shared system C libraries work fine for most users), but if this is the case for you, download and use the `rEFInd_GUI_standalone.tar.gz` version. Both of these can be found on the [release](https://github.com/jlobue10/SteamDeck_rEFInd/releases) page.

**Comment by WojtekHenszke** [comment]
Not sure if this could be the case, but the only not `Vanilla` thing that I could suspect would be a use of `zsh` instead of whatever shell is used on deck

**Comment by jlobue10** [comment]
Unless it's a dependency, or something else installed alongside `zsh`, I don't think that's the culprit. It's honestly a strange issue that I have not been able to reproduce for troubleshooting on my end. I also can't really justify spending too much time trying to do so when good workarounds or solutions exist (download precompiled tarball versions, regular or standalone).

Off topic, but I also like `zsh` and use it with `Oh-My-Zsh` on multiple Kubuntu rigs that I manage.

**Comment by heems347** [comment]
> Yes, I've seen compile errors before from other users, but I've never been able to replicate the errors in my own testing. My solution is for those who experience these compile errors to download the `rEFInd_GUI.tar.gz` tarball and extract the whole directory to `/home/deck`. For the even rarer case(s), the compiled version with static C libraries is provided. Again, I have not ever been able to replicate why some people need this static C library version and others do not (shared system C libraries work fine for most users), but if this is the case for you, download and use the `rEFInd_GUI_standalone.tar.gz` version. Both of these can be found on the [release](https://github.com/jlobue10/SteamDeck_rEFInd/releases) page.

hey how are doing i ran into same issue with my deck, i downloaded the tar.gz and extracted it to my home/deck file, but i am lost on how to move forward from there. 

very respectfully,

RA

**Comment by jlobue10** [comment]
Basically if you copy the rEFInd_GUI.desktop shortcut to the desktop, then double click it to run. Assuming you copied the directory correctly to `/home/deck`, then it should run. If it does nor, you may need to use the `standalone` version.

**Comment by heems347** [comment]
ok going to try it now thank you will update in a few

**Comment by heems347** [comment]
> Basically if you copy the rEFInd_GUI.desktop shortcut to the desktop, then double click it to run. Assuming you copied the directory correctly to `/home/deck`, then it should run. If it does not run, then you may need to use the `standalone` version.

yea i right click to extract and set to the deck folder, it shows completed but, nothing show up

**Comment by jlobue10** [comment]
It's a hidden folder. You have to enable the 'Show Hidden folders' option to see it in Dolphin.

**Comment by heems347** [comment]
> It's a hidden folder. You have to enable the 'Show Hidden folders' option to see it in Dolphin.

ok got it now i can move on the next steps thank you and where did you get that mario back grounds that looks so cool

**Comment by jlobue10** [comment]
You'd have to ask Deck Wizard about the Mario background. Glad that you've made progress.

**Comment by jlobue10** [comment]
These compile issues should not be an issue moving forward as I will just be compiling myself and uploading the results of makepkg using updated PKGBUILD.
