### ISSUE TITLE
Mouse on screen?

### ISSUE THREAD

**Issue by OGMcSkillet** [jlobue10/SteamDeck_rEFInd#6]
installed well but i see a mouse in the middle of the screen, how do i remove it? as i can chose with the dpad i dont think its needed.

**Comment by jlobue10** [comment]
You can comment out the `enable_mouse` line in the `refind.conf` config file. Back when I initially wrote this script, the D-PAD was not working on the latest SteamOS stable release. It seems to have been fixed since then.

**Comment by jlobue10** [comment]
Mouse setting can be disabled by changing (or commenting out) the applicable option in the `refind.conf` config file.
