### ISSUE TITLE
SteamOS doesn't boot anymore

### ISSUE THREAD

**Issue by DandeMC** [jlobue10/SteamDeck_rEFInd#61]
Hi,

I installed SteamOS new, then refind and then windows 11. After I disabled the windows boot manager from the recovery stick, I can't boot steamos anymore. Not from refind loader or directly. Windows boots.
What can I do?

**Comment by jlobue10** [comment]
That's a bit out of order that I'd recommend (do rEFInd last in the future). Show me the output of `efibootmgr` from a SteamOS command line and show me what your `refind.conf` file looks like. I will need these things if I'm going to be able to help, as they give me most of the information that I'm interested in for troubleshooting something like this.

**Comment by jlobue10** [comment]
Try to boot from the SteamOS EFI file directly by powering on with Vol+Up and Power and going to boot from file, `/esp/efi/steamos/steamcl.efi`, before reimaging. We can likely salvage this another less destructive way (or at least it's worth trying to first).

**Comment by DandeMC** [comment]
I tested this and my steam deck shows only a black screen. I waited 10 minutes. I think the efi file was broken after the windows 11 installation. But I don't know why.

**Comment by jlobue10** [comment]
Try the reinstall SteamOS option before reimaging. A lot of situations can be fixed with that option and it leave installed games, saved games, configurations, and Windows partitions in tact. I go over the steps required to restore the Windows EFI entry and boot files after a SteamOS reinstall here.

**Comment by DandeMC** [comment]
It's to late. I used the reimaging option. But it's okay. I haven't any games on that. My steam deck arrived today. 
Now I will install steamos again, then windows 11. Both on the internal ssd. And after that, I will install refind with your script. I hope that works 😊

**Comment by DandeMC** [comment]
Thx for your help. After reinstallation it works perfektly!
