### ISSUE TITLE
Can't remove rEFIND

### ISSUE THREAD

**Issue by Octave1904** [jlobue10/SteamDeck_rEFInd#64]
![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/134335505/0f1c7ad9-823c-4897-9678-e721242166ff)

**Comment by Octave1904** [comment]
I'm sorry to ask your help but I can't remove rEFIND of my steam deck... could you help me pls ?

**Comment by jlobue10** [comment]
Are you trying to completely remove rEFInd or just to disable it to reinstall Windows? Are you following the instructions on my GitHub page or someone else's? My repo does not use a `~/1rEFInd-tools` folder.

**Comment by Octave1904** [comment]
I try to completely remove rEFInd but it dosen't work(I followed the instructions ^^)

**Comment by Octave1904** [comment]
![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/134335505/feef1d58-cace-4902-92c4-46242720d27b)
I just want to remove this screen

**Comment by jlobue10** [comment]
The quickest way would be to change the commands you typed to be:

```
sudo efibootmgr -b 0002 -B
```

```
sudo efibootmgr -b 0004 -B
```

Removing the files would require some additional steps, as outlined in the README.

**Comment by MADOK1** [comment]
"/path/to/refind-executable" isn't literally the path to the refind executable, it's just a placeholder.

**Comment by Kirit29** [comment]
> The quickest way would be to change the commands you typed to be:
> 
> ```
> sudo efibootmgr -b 0002 -B
> ```
> 
> ```
> sudo efibootmgr -b 0004 -B
> ```
> 
> Removing the files would require some additional steps, as outlined in the README.

When I do this the entry keeps coming back on a second reboot

**Comment by Octave1904** [comment]
Same here

**Comment by jlobue10** [comment]
You need to also delete the Microsoft folder on the `/esp` partition.
