### ISSUE TITLE
Can't compile GUI

### ISSUE THREAD

**Issue by JinKusanagi** [jlobue10/SteamDeck_rEFInd#65]
This is probably just a really dumb easy fix but this morning I installed the GUI from konsole on my steam deck and it worked fine. However I had to reimage the internal drive and now when I go through the process again it gives me this error.

error: failed to synchronize all databases (failed to retrieve some files)
/usr/bin/uic mainwindow.ui -o ui_mainwindow.h
g++ -c -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT
_CORE_LIB -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I
. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o main.o main.cpp
In file included from main.cpp:1:
mainwindow.h:4:10: fatal error: string: No such file or directory
   4 | #include <string>
     |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:800: main.o] Error 1

GUI compile failed. Please try again after ensuring that your cloned repo is up to date and your pacman config
is normal.

I tried the reset --hard command but it still gives the same error. I also checked to make sure there was a password set in the user settings. I don't really understand why for some reason the compiler no longer works. I did go through the initial steam OS setup. Is there another step I forgot somewhere?

**Comment by JinKusanagi** [comment]
Update I realized my problem was similar to the qmake unable to compile problem. I tried downloading both the rEFInd.tar.gz and the standalone but neither work. I extracted to home/deck but after running the desktop shortcut from desktop does nothing. No window even shows up it just closes.

**Comment by JinKusanagi** [comment]
I tried the alternate install with the stand alone still no luck. Checking the pacman.conf shows all my repositories are just 
[jupiter]
[holo]
[core]
[extra]
[community]
[multilib]
And they all fail to download because of 404 errors. Should I change them to rel even though they weren't listed as beta?

**Comment by jlobue10** [comment]
> Update I realized my problem was similar to the qmake unable to compile problem. I tried downloading both the rEFInd.tar.gz and the standalone but neither work. I extracted to home/deck but after running the desktop shortcut from desktop does nothing. No window even shows up it just closes.

You extracted the entire `.SteamDeck_rEFInd` folder to `/home/deck` and the standalone version still does not run? This is strange and definitely not what I'd expect. If you open up a Konsole and change into the `/home/deck/.SteamDeck_rEFInd` folder, try to run `./rEFInd_GUI` from there. What happens? Does it launch or do you get any error message in the terminal output?

**Comment by JinKusanagi** [comment]
Sorry I'm not quite sure what your asking me to run but running ./rEFInd_GUI in /home/deck/.SteamDeck_rEFInd/GUI gives

[deck@steamdeck GUI]$ ./rEFInd_GUI
./rEFInd_GUI: /usr/lib/libc.so.6: version `GLIBC_2.36' not found (required by ./rEFInd_GUI)
./rEFInd_GUI: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by ./rEFInd_GUI)
./rEFInd_GUI: /usr/lib/libc.so.6: version `GLIBC_2.35' not found (required by ./rEFInd_GUI)

This was the only place I could find "rEFInd_GUI"

To confirm a few things I have both SteamDeck_rEFInd and .SteamDeck_rEFInd in my home directory.
And for what its worth running  [deck@steamdeck GUI]$ ./refind_GUI.desktop gives

./refind_GUI.desktop: line 1: [Desktop: command not found
./refind_GUI.desktop: line 3: Customization: command not found
./refind_GUI.desktop: line 5: GUI: command not found
./refind_GUI.desktop: line 7: GUI: command not found
./refind_GUI.desktop: line 12: X-KDE-SubstituteUID=false: command not found
[deck@steamdeck GUI]$ ls

**Comment by jlobue10** [comment]
Yes I forgot that GUI was in the command path. The correct path to run `rEFInd_GUI` from is `/home/deck/.SteamDeck_rEFInd/GUI`. Are you sure that you're running the standalone version? The standalone version is meant to correct C library issues on some Steam Decks.

**Comment by JinKusanagi** [comment]
Sorry for the slow reply yes I have extracted the standalone zip and am in the /.SteamDeck_rEFInd folder which is the hidden one I extracted.

**Comment by jlobue10** [comment]
What's the output of `md5sum rEFInd_GUI`?

**Comment by JinKusanagi** [comment]
Here you go 
![GitScreen](https://github.com/jlobue10/SteamDeck_rEFInd/assets/53881454/80d9df9d-73d9-45ac-977b-963843d2491f)

**Comment by jlobue10** [comment]
Okay, thank you for this. I'm in the midst of finishing up a move, so my detailed troubleshooting is hindered at the moment. I understand your issue more clearly now. Please give me a little time for further troubleshooting on my end. I'm sorry for your difficulties, as the standalone version has worked for others in similar situations in the past. I may need to update some compile settings for the standalone version.

**Comment by JinKusanagi** [comment]
Its okay thank you for the help. Its really weird because I had installed it on my steam deck once already but then had to re image sine the partitions got a bit messed up. Hope you can figure it out so I can have a GUI again!

**Comment by jlobue10** [comment]
> I tried the alternate install with the stand alone still no luck. Checking the pacman.conf shows all my repositories are just [jupiter] [holo] [core] [extra] [community] [multilib] And they all fail to download because of 404 errors. Should I change them to rel even though they weren't listed as beta?

You can try adding the `-rel` to each and see how far the GUI installer gets. If the compile still fails, maybe the standalone version will then work. It's worth a try.

**Comment by JinKusanagi** [comment]
![relTest1](https://github.com/jlobue10/SteamDeck_rEFInd/assets/53881454/35721727-4887-4ce8-a961-ebfabe0a8367)
![relTest2](https://github.com/jlobue10/SteamDeck_rEFInd/assets/53881454/7f0d17b8-a1db-4ffd-9cee-11064171744c)

Ok so I tried switching the DBs to rel and the installer seemed to run but gave a bunch of corrupted package errors as shown in the screenshots. I tried running the refind_install_pacman_GUI.sh which said it completed but when I ran rEFInd.GUI it threw the same GLIBC_2.36,4,and 5 errors it did before. Running the no_pacman install gives 

[deck@steamdeck .SteamDeck_rEFInd]$ ./refind_install_no_pacman_GUI.sh 
./refind_install_no_pacman_GUI.sh: line 19: wget: command not found
unzip:  cannot find or open refind-bin-gnuefi-0.14.0.2.zip, refind-bin-gnuefi-0.14.0.2.zip.zip or refind-bin-gnuefi-0.14.0.2.zip.ZIP.
cp: cannot stat '/home/deck/Downloads/refind-bin-0.14.0.2/refind/refind_x64.efi': No such file or directory
cp: cannot stat '/home/deck/Downloads/refind-bin-0.14.0.2/refind/drivers_x64/': No such file or directory
cp: cannot stat '/home/deck/Downloads/refind-bin-0.14.0.2/refind/tools_x64/': No such file or directory
sudo: ./refind-bin-0.14.0.2/refind-install: command not found
cp: cannot stat '/home/deck/Downloads/refind-bin-0.14.0.2/refind/icons/': No such file or directory
cp: cannot stat '/home/deck/Downloads/refind-bin-0.14.0.2/fonts/': No such file or directory
Invalid bootnum value: FFFFFFFFFFFFFFF5

Hope this helps some how I'm going to change the DBs back to normal in case it messes with something else.

**Comment by jlobue10** [comment]
Just for my knowledge, did you perform the re-image through the SteamOS recovery USB, or the factory reset option from within the SteamOS menus?

**Comment by JinKusanagi** [comment]
I did it through a SteamOS recovery USB

**Comment by jlobue10** [comment]
It's possible that one of these installers overwrote your `refind.conf` file with an improper config for your setup. Did you see my question above? I've never personally encountered errors like this, and I've never been able to replicate them on my end.

**Comment by jlobue10** [comment]
> I did it through a SteamOS recovery USB

Thanks for confirming. I may need to look into a more comprehensive compile for the standalone version. Things are still slow as my workspace is still not properly setup at home. I apologize for the delays in fixing your issue.

**Comment by jlobue10** [comment]
So I'm thinking that I need to update the line that I use for the standalone version compile from

'''
QMAKE_LFLAGS += -static-libgcc -static-libstdc++
```

to

```
QMAKE_LFLAGS += -static-glibc -static-libgcc -static-libstdc++
```
or something along those lines. Your particular issue seems most likely to be with `glibc`, so it will need to be compiled into the GUI statically to work.

This may also require some extra prep steps on my end to successfully complete the compile. This seems to be a new issue that you're experiencing compared to similar issues experienced by others in the past. This may take some time to properly vet and fix since my home workstation and office is not really set up yet. Again, I apologize for the inconvenience, but I will find a fix and release it as soon as I can. Thanks.

**Comment by JinKusanagi** [comment]
I understand I'll just be glad to have it working once again eventually. Thank you for the help good luck in figuring it all out.

**Comment by jlobue10** [comment]
I'm curious as to the results if you run these one after the other. I started investigating a compile update for you and `make` was not found in the path which I found very odd. I was able to fix it by reinstalling some packages, but there was a hiccup along the way with `fakeroot`. Maybe you are experiencing something similar. It's at least worth looking into.

```
sudo steamos-readonly disable
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Sy base-devel
```

That group package (set of 26) initially had an error with `fakeroot` until I ran these to try again (which was successful).

```
sudo rm /etc/ld.so.conf.d/fakeroot.conf
sudo pacman -Sy base-devel
```

If you see a `fakeroot` error trying to install the `base-devel` package group, could you try what worked for me?

**Comment by JinKusanagi** [comment]
Sorry It took me a while to try this I'm getting ready to travel. Here is what happened.

![pacman_tests1](https://github.com/jlobue10/SteamDeck_rEFInd/assets/53881454/f325f6b7-5536-44da-908b-7737b01cf876)
![pacman_tests](https://github.com/jlobue10/SteamDeck_rEFInd/assets/53881454/417f6eb7-3029-4c95-831c-b058b85aedb3)

So I seem to have gotten the same 404 errors from the non *-rel DBs and I did not have a fakeroot.conf at least not at the path provided. Upon changing the dbs to *-rel and running the commands again konsole told me all DBs were up to date except Jupiter-rel. It began downloading the packages but then proceeded to tell me they were either not trusted or corrupted. I didn't install any of them but should I? Is it just a weird bug that they aren't trusted for some reason? All the packagers that were corrupted were the ones I need right? I guess I will also keep all the DBs as *-rel to see if it changes anything in my steamOS. If it doesn't I guess I'll just keep them as *-rel

**Comment by jlobue10** [comment]
Interesting. So if you run `sudo ls -alh /var/cache/pacman/pkg` are those `.zst` files still actually there after saying to delete them? If so, you can try deleting them with `sudo rm` for each of those files. Be careful with this command and only delete those files you intend to with that. Then try to install the `base-devel` package group again. If it still fails, then I think we may be hard stuck on this as a blocker.

If it somehow does work after deleting those old signature files, then please try to also install `sudo pacman -Sy lib32-glibc glibc hwinfo linux-api-headers qt5-base` (maybe do this anyways, regardless if the `base-devel` installation is successful or not). From looking at your issue so far, the most common error seems to be with `glibc` so if we can get the `glibc` (and `lib32-glibc`) package(s) to install at a minimum, then you might be okay to get the standalone precompiled version working. I've been looking into a more in depth static library compile that removes some additional system provided dependencies, but this is still a work in progress. My preference would be that these packages are just included by default in future versions of SteamOS, as they take up very little space and allow my program to compile without issue.

Let me know how it goes. Thanks.

**Comment by JinKusanagi** [comment]
![pkgs](https://github.com/jlobue10/SteamDeck_rEFInd/assets/53881454/9818be23-d1f4-4045-a95c-c4d8a21259df)

The packages were gone. Attempting the base-devel again gave the same corrupt errors. 
I tried running the other line for a pacman install of glibc but it also said all 4 .zsts were corrupt. 
Should I be asking steam support about this is this an issue with my OS or something. Like maybe when I reimaged something messed up?

![ManualPacman](https://github.com/jlobue10/SteamDeck_rEFInd/assets/53881454/d04e90df-1463-4e0c-b49a-2d01459040ad)

**Comment by jlobue10** [comment]
This is one of those strange set of errors that I've only encountered a handful of times previously. In those previous examples, the standalone version was able to work. Your case seems unique. I would be inclined to think something was off with your reimage compared to other users. If it were not a huge pain on your end, I'd suggest creating a fresh SteamOS recovery USB and re-trying the re-image process. If that is too much, then we could potentially manually download and build (and install) the packages and dependencies that we need with `makepkg` and `makepkg --install`, but this is a bit time consuming as well and may not persist with OS updates or switches from rootA to rootB partitions. SteamOS is not really meant to be tinkered with too much in this way which is why I'd hope these basic packages would just be included in future releases, but time will tell. Providing this resource on this repo in this way and including my source files allows the code to be audited and people to check for and make potential improvements (if any are to be had or are worth the effort of code changes).

Let me know how you want to proceed. I can also continue to look into a more in-depth static library compiled version that would hopefully work for your case, but I have not been able to fully vet and test that option yet.

**Comment by JinKusanagi** [comment]
I am inclined to reimage but since I'm traveling soon having a working dual boot is good enough for now. I do plan to upgrade the internal SSD at some point so at that time I'll make a fresh recovery USB and retry the GUI. I am a little interested in the alternative solutions but I don't think I have the time currently. Thank you for all your help.

If I do want to revisit this issue is there somewhere I should contact you or will this issue remain open?

**Comment by jlobue10** [comment]
I'll keep the issue open. I'm almost certain that we could get around the `pacman` problems by manually downloading, building and installing packages, as this is something that I'm having to do in my static library compile investigation. I also think that this is way more effort than most people would want to do for this. I'll comment more details in a future comment, if for no other reason than for reference purposes.

**Comment by darrylmorley** [comment]
I had the same issue, re-imaged the Steam Deck and it worked fine.

**Comment by jlobue10** [comment]
These compile issues should not be an issue moving forward as I will just be compiling myself and uploading the results of makepkg using updated PKGBUILD.

Please try the new installer and let me know how it goes.
