### ISSUE TITLE
suggested feature: UEFI only boot config save and restore system

### ISSUE THREAD

**Issue by c0de90e7** [jlobue10/SteamDeck_rEFInd#66]
Hi,

I don't know if this is the correct place to suggest this and I don't even know if this is usable or integrable here, but it may at least serve as an idea...

I have prepared a small pack, two scripts and two shell.efi ( the regular, official shell ) files modified to run one of those two scripts each, instead of running the standard startup.nsh. These modified shell.efi files, called savecfg.efi and fixboot.efi, are there just for the purpose of running cfgsave.nsh and bootfix.nsh respectively.

cfgsave.nsh will just run dmpstore BootOrder -s BootOrder.sav and dmpstore <Boot0000..0009> -s <Boot0000..0009.sav> and bootfix.nsh will just run dmpstore BootOrder -l BootOrder.sav and dmpstore <Boot0000..0009> -l <Boot0000..0009.sav>. So, basically, cfgssve.nsh will save the UEFI variables for boot configuration and bootfix.nsh will restore the saved configuration.

When the user has everything setup properly, be it with rEFInd or with Clover, whatever the config may be, boot the Deck with VOL+, choose Boot via file and run savecfg.efi. This will run cfgsave.nsh which will save all boot configuration.

Whenever the user updates SteamOS and the UEFI boot variables get deleted/broken, boot the Deck with VOL+, choose Boot via file and run fixboot.efi. This will run bootfix.nsh which will restore the previously saved boot configuration.

These modified shell.efi files I just hexedited them and changed startup.nsh string to cfgsave.nsh/bootfix.nsh, I know this is not the orthodox way but it was the easiest/quickest way to test this. Two proper UEFI apps that substitute these two hacked .EFI files and the two scripts would also work. However, it may still be a good idea to do it via these scripts, since they can be user-edited to do some other ad-hoc things.

Pardon me for this unorthodox way of providing this.

.ZIP file with the files: https://fastupload.io/w29IZwoEoJPqk5E/file

NOTE: the .ZIP file has the structure needed, that is, the two .NSH files should be in the root folder and the two .EFI files should be into the EFI folder. This is not strictly required, the .NSH files are easier found in the root folder but the .EFI files can actually go anywhere. However, some rEFInd configurations will make it so that the .EFI files found in the root folder will be shown as boot options/entries, putting them into the EFI folder ( but not into another subfolder into EFI ) will avoid this, they will not appear as rEFInd boot entries.

**Comment by jlobue10** [comment]
This seems interesting but it's not something that I'm going to pursue adding to this repository. My main reasons being that the `systemd` daemon is basically already performing a similar functionality when SteamOS boots by checking for missing EFI entries for SteamOS and rEFInd,  adding them back if they are missing, and then setting rEFInd as the `BootNext` EFI option.

I also don't want to add this as it's a possibility for people to manipulate for malicious purposes in the future. Please feel free  to fork the repo and add or create a new repo with just this. Thanks for the idea and input.

**Comment by c0de90e7** [comment]
Ok, yes, I understand.

Thank you anyway :)
