### ISSUE TITLE
Windows 10 higher boot priority

### ISSUE THREAD

**Issue by Samurott1922** [jlobue10/SteamDeck_rEFInd#67]
rEFInd is working as intended, I have my Steam OS on the Steam Deck NVME and Windows 10 on my SD card, and during boot, both icons work perfectly. However when I attempted to restart out of Windows 10 its just booted back into Windows 10 and skipped rEFInd. So I held the power and volume buttons to check the boot menu and Windows 10 is directly above rEFInd? How do I fix this and what did I screw up?

Here is my refind.conf file
[refind.txt](https://github.com/jlobue10/SteamDeck_rEFInd/files/11733531/refind.txt)

**Comment by monroth** [comment]
Neither of these solutions work for me. If i delete Windows efi entry, upon next start of Windows it automatically creates it again. For example, if i just reorder boot order (via efibootmgr), Windows will make itself boot without even needing to start it first. 

When I try workaround, when I press "run" to check if task is working, no shell is appearing and it's status changes to "running" without real end. If I manually try to do what this task writes something, and i'm not sure if it is what is correct.
```
C:\Windows\system32>C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -executionpolicy bypass -file C:\rEFInd\SteamDeck_rEFInd-main\Windows\bootsequence-rEFInd-first.ps1
The entry list data is not valid as specified.
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.
The operation completed successfully.
```
when i run bcdedit /enum FIRMWARE command, it shows this
```
C:\Windows\system32>bcdedit /enum FIRMWARE

Firmware Boot Manager
---------------------
identifier              {fwbootmgr}
displayorder            {bootmgr}
                        {2c7da82a-0a18-11ee-b1b9-806e6f6e6963}
                        {14917104-078e-11ee-b1a4-806e6f6e6963}
                        {ec188ef2-0a07-11ee-b1b4-806e6f6e6963}
                        {dcc85902-7515-11e7-ad93-cb4d371853a5}
                        {e024e0f9-070c-11ee-b19f-806e6f6e6963}
                        {e024e0f7-070c-11ee-b19f-806e6f6e6963}
                        {e024e0f8-070c-11ee-b19f-806e6f6e6963}
timeout                 0

Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  partition=\Device\HarddiskVolume2
path                    \EFI\refind\refind_x64.efi
description             Windows Boot Manager
locale                  en-us
inherit                 {globalsettings}
default                 {current}
resumeobject            {fb084468-00e0-11ee-a176-90fcc820d8a3}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 5

Firmware Application (101fffff)
-------------------------------
identifier              {14917104-078e-11ee-b1a4-806e6f6e6963}
device                  partition=\Device\HarddiskVolume1
path                    \EFI\ubuntu\shimx64.efi
description             ubuntu

Firmware Application (101fffff)
-------------------------------
identifier              {2c7da82a-0a18-11ee-b1b9-806e6f6e6963}
device                  partition=\Device\HarddiskVolume1
path                    \EFI\Microsoft\Boot\bootmgfw.efi
description             Windows Boot Manager

Firmware Application (101fffff)
-------------------------------
identifier              {dcc85902-7515-11e7-ad93-cb4d371853a5}
device                  partition=\Device\HarddiskVolume1
path                    \EFI\steamos\steamcl.efi
description             SteamOS

Firmware Application (101fffff)
-------------------------------
identifier              {e024e0f7-070c-11ee-b19f-806e6f6e6963}
description             EFI DVD/CDROM

Firmware Application (101fffff)
-------------------------------
identifier              {e024e0f8-070c-11ee-b19f-806e6f6e6963}
description             EFI Network

Firmware Application (101fffff)
-------------------------------
identifier              {e024e0f9-070c-11ee-b19f-806e6f6e6963}
description             EFI USB Device

Firmware Application (101fffff)
-------------------------------
identifier              {ec188ef2-0a07-11ee-b1b4-806e6f6e6963}
device                  partition=\Device\HarddiskVolume1
path                    \EFI\refind\refind_x64.efi
description             rEFInd
```
and although first entry says that it's path is  \EFI\refind\refind_x64.efi (and showed it even before I tried workaround), it does not matter, as it boots windows, and not refind.

**Comment by monroth** [comment]
when i boot in linux, it however says 
```
deck@Steam-Deck-Monroth:~$ efibootmgr -v
Timeout: 0 seconds
BootOrder: 0000,0004,0005,0003,2001,2002,2003
Boot0000* Windows Boot Manager	HD(1,GPT,7fe8b3b5-e527-544b-9c35-b1ef73a4cb92,0x800,0x20000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)RC
Boot0003* SteamOS	HD(1,GPT,7fe8b3b5-e527-544b-9c35-b1ef73a4cb92,0x800,0x20000)/File(\EFI\steamos\steamcl.efi)
Boot0004* ubuntu	HD(1,GPT,7fe8b3b5-e527-544b-9c35-b1ef73a4cb92,0x800,0x20000)/File(\EFI\ubuntu\shimx64.efi)RC
Boot0005* rEFInd	HD(1,GPT,7fe8b3b5-e527-544b-9c35-b1ef73a4cb92,0x800,0x20000)/File(\EFI\refind\refind_x64.efi)
Boot2001* EFI USB Device	RC
Boot2002* EFI DVD/CDROM	RC
Boot2003* EFI Network	RC
```
I.e. another path for "Windows Boot Manager". No idea what is happening here.

**Comment by jlobue10** [comment]
> Neither of these solutions work for me. If i delete Windows efi entry, upon next start of Windows it automatically creates it again. For example, if i just reorder boot order (via efibootmgr), Windows will make itself boot without even needing to start it first.
> 
> When I try workaround, when I press "run" to check if task is working, no shell is appearing and it's status changes to "running" without real end. If I manually try to do what this task writes something, and i'm not sure if it is what is correct.

So I don't think you actually did either of the methods that I suggested properly. Let's go over this in detail in case the README is confusing.

To disable (not delete, and there is a difference in this context) the Windows EFI entry using `efibootmgr` you need to boot into the SteamOS recovery image (or another Linux distro). From that session, determine the 4 digit number for your Windows EFI entry. From your `efibootmgr` output above, I can see `0000`. The correct command to disable it would be `sudo efibootmgr -b 0000 -A`.

I can see that you also have an Ubuntu entry. You will also need to disable this Ubuntu entry so that rEFInd can assume a higher boot priority. The command would be `sudo efibootmgr -b 0004 -A`.You can tell if the entry is disabled or not in the `efibootmgr` output by whether or not the asterisk disappears. If the asterisk is gone, then the entry is disabled. Hopefully this is more clear to you now. There is also a batch file you can run from Windows as an alternative, but I'd suggest sticking with this `efibootmgr` approach.

**Comment by Samurott1922** [comment]
I attempted 
`sudo efibootmgr -b 0003 -A`
Which then produced
`efibootmgr: Boot entry 3 not found`
`Could not set active state for Boot0003: No such file or directory`

In Konsole I verified that 0003 is my Windows Boot Manager

**Comment by jlobue10** [comment]
Show me the output of just `efibootmgr`. Also, did you boot into the SteamOS recovery USB, or just regular SteamOS? This has been a known bug since version 3.4 that this particular `efibootmgr` command would not work properly in regular SteamOS (and give this exact error).

**Comment by Samurott1922** [comment]
efibootmgr
BootNext: 0004
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0003,0004,0002,0000,0001,2001,2002,2003
Boot0000* EFI Hard Drive (50026B76856E6421-KINGSTON OM3PDP3512B-A01)    PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/NVMe(0x1,00-26-B7-68-56-E6-42-15)/HD(1,GPT,27bd1145-0922-a94f-b256-8df6bd39e819,0x800,0x20000)RC
Boot0001* EFI SD/MMC Card (DS T10N ﾥﾑￗ) PciRoot(0x0)/Pci(0x1,0x3)/Pci(0x0,0x0)/SD(0)/HD(1,GPT,dc7d733f-54e0-49db-8f38-14bef897cb20,0x800,0x82000)RC
Boot0002* SteamOS       HD(1,GPT,27bd1145-0922-a94f-b256-8df6bd39e819,0x800,0x20000)/File(\EFI\steamos\steamcl.efi)
Boot0003* Windows Boot Manager  HD(1,GPT,dc7d733f-54e0-49db-8f38-14bef897cb20,0x800,0x82000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)57494e444f5753000100000088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d0034006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000000000100000010000000040000007fff0400
Boot0004* rEFInd        HD(1,GPT,27bd1145-0922-a94f-b256-8df6bd39e819,0x800,0x20000)/File(\EFI\refind\refind_x64.efi)
Boot2001* EFI USB Device        RC
Boot2002* EFI DVD/CDROM RC
Boot2003* EFI Network   RC



And I did do it in SteamOS, I will try in the Recovery mode now

**Comment by Samurott1922** [comment]
That did it, thanks for the awesome script!
