### ISSUE TITLE
I got corrupted display issues in ubuntu 20.04.

### ISSUE THREAD

**Issue by sizsJEon** [jlobue10/SteamDeck_rEFInd#68]
after first install and few run,

it bootup with no problems.

but after that, it shows corrupted display and sometimes or get black screen (nothing shows in display)

when I set #resolution 3 at sudo nano /esp/efi/refind/refind.conf,
ubuntu bootup with rotated display.
and I fixed /etc/default/grub with GRUB_GFXMODE=1024x768

but after come back to resolution 3, 
ubuntu shows corrupted display at startup and got black screen.

any suggestion for improvement please.

**Comment by jlobue10** [comment]
Is there any reason that you haven't updated to 22.04 LTS? 20.04 may have some packaging issues that are causing this (would be what I'd suspect more than anything). I never experienced this with Kubuntu 22.04 loading its GRUB (so i can select which kernel to boot) from rEFInd.

**Comment by sizsJEon** [comment]
> Is there any reason that you haven't updated to 22.04 LTS? 20.04 may have some packaging issues that are causing this (would be what I'd suspect more than anything). I never experienced this with Kubuntu 22.04 loading its GRUB (so i can select which kernel to boot) from rEFInd.

I should run ros1(http://wiki.ros.org/noetic/Installation/Ubuntu) on this machine for now.
there are some repo that install ros1 on steamos with conda pacakge,
but I'm trying to use it as a separate operating system and within ubuntu os.

**Comment by stereochuck** [comment]
Any solution on this?
It worked fine for few boots but then after some install (like php and mysql and stuff) I have a black screen with corrupted display at boot with what I assume is blinking text (can't read anything on the deck or monitor). I reinstalled Ubuntu few times already, I had issue with black screen with and without corrupted gibberish text.

**Comment by jlobue10** [comment]
Show me the output of `efibootmgr` and the contents of your installed `refind.conf` file (`sudo nano /esp/efi/refind/refind.conf`). I'd like to see what these show from a SteamOS command line.

I need more information (which is why I ask) to comment further. I've moved on to Nobara personally (from Kubuntu) on my own personal Steam Deck for a non-immutable Linux distro at the end of my 2TB drive (100GB given to it).

**Comment by stereochuck** [comment]
I use my deck to work so I'm hesitant to execute `apt upgrade` right now, I will do it asap tho.
