### ISSUE TITLE
Is there any reason why SteamDeck_rEFInd has four slots?

### ISSUE THREAD

**Issue by feraleyebrows** [jlobue10/SteamDeck_rEFInd#69]
Just curious as to whether there is any reason why it's hardcoded to four slots, was it just an arbitrary choice or is there some kind of limitation? The Steam Deck has got me venturing into Linux land for the first time in over a decade so I was toying with the idea of having a few different distros on SD cards and using SteamDeck_rEFInd to swap between them.

**Comment by jlobue10** [comment]
It was mainly a design choice to cover the vast majority of desired use cases. It sounds like you might benefit from using the `Ventoy` option from rhe SD card. You can add multiple live Linux ISOs to try different distros that way, quite easily.
