### ISSUE TITLE
Boot Menu does Not Display

### ISSUE THREAD

**Issue by andrewkhunn** [jlobue10/SteamDeck_rEFInd#7]
Just installed the latest release via basica instructions and I do not have any rEFInd boot menu displayed on startup. I get a mouse cursor with a blank black screen, hit the timeout of 5 seconds, and then boot straight into Steam OS (whereas previously I would've booted straight into Win11).

Reran the installer again for good measure and don't see many suspicious entries in the install log. Only thing that looked possibly out of place was a package manager complaining what I assume was refind could not be found in the steamos package repo.

Everything seems to function correctly, but I just don't seem to get any boot menu display for some reason. Any ideas?

**Comment by jlobue10** [comment]
Can you please give me the command line dump for the error that you're seeing? I have not encountered this error personally in any of my testing. Maybe something is going on with the latest SteamOS changes. You should see icons for SteamOS and Windows (when booting with the rEFInd menu) if all went well, and they should be selectable with either the mouse cursor or the D-PAD.

**Comment by andrewkhunn** [comment]
It appears as though there might have just been a momentary outage of the repo that refind was getting pulled from, as I just reran the install script again and everything is working as intended.

Sorry for the confusion and thanks for the tool itself!
