### ISSUE TITLE
GUI compile failed

### ISSUE THREAD

**Issue by ghost** [jlobue10/SteamDeck_rEFInd#71]
Errors occurred, no packages were upgraded.
:: Synchronizing package databases...
 jupiter-rel is up to date
 holo-rel is up to date
 core-rel is up to date
 extra-rel is up to date
 community-rel is up to date
 multilib-rel is up to date
warning: lib32-glibc-2.36-6 is up to date -- reinstalling
warning: glibc-2.36-6 is up to date -- reinstalling
warning: hwinfo-22.1-1 is up to date -- reinstalling
warning: linux-api-headers-5.18.15-1 is up to date -- reinstalling
warning: qt5-base-5.15.6+kde+r180-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (5) glibc-2.36-6  hwinfo-22.1-1  lib32-glibc-2.36-6
             linux-api-headers-5.18.15-1  qt5-base-5.15.6+kde+r180-1

Total Installed Size:  137.16 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n]
(5/5) checking keys in keyring                      [##########################] 100%
(5/5) checking package integrity                    [##########################] 100%
(5/5) loading package files                         [##########################] 100%
(5/5) checking for file conflicts                   [##########################] 100%
(5/5) checking available disk space                 [##########################] 100%
:: Processing package changes...
(1/5) reinstalling linux-api-headers                [##########################] 100%
(2/5) reinstalling glibc                            [##########################] 100%
warning: directory permissions differ on /var/db/
filesystem: 711  package: 755
Generating locales...
  en_US.UTF-8... done
Generation complete.
(3/5) reinstalling lib32-glibc                      [##########################] 100%
(4/5) reinstalling hwinfo                           [##########################] 100%
(5/5) reinstalling qt5-base                         [##########################] 100%
:: Running post-transaction hooks...
(1/4) Reloading system manager configuration...
(2/4) Creating temporary files...
/usr/lib/tmpfiles.d/steamos.conf:24: Duplicate line for path "/var/empty", ignoring.
/usr/lib/tmpfiles.d/tmp.conf:12: Duplicate line for path "/var/tmp", ignoring.
/usr/lib/tmpfiles.d/var.conf:19: Duplicate line for path "/var/cache", ignoring.
(3/4) Arming ConditionNeedsUpdate...
(4/4) Updating the info directory file...
Project ERROR: Cannot run compiler 'g++'. Output:
===================
===================
Maybe you forgot to setup the environment?
make: *** No targets specified and no makefile found.  Stop.

GUI compile failed. Please try again after ensuring that your cloned repo is up to date and your pacman config is normal.

Been getting this issue every time I try to install it, this is also after a fresh factory reset from the steam decks software (Thought it would eliminate this error but it gave me a completely new one) No clue where to go from here since no-one else seems to have this issue either

**Comment by jlobue10** [comment]
Can you try the precompiled version? If that doesn't work, please try the standalone precompiled version. More info is available [here](https://github.com/jlobue10/SteamDeck_rEFInd/tree/main/GUI).

**Comment by KittumsVR** [comment]
> Can you try the precompiled version? If that doesn't work, please try the standalone precompiled version. More info is available [here](https://github.com/jlobue10/SteamDeck_rEFInd/tree/main/GUI).

Is this the right one to download? The link you sent I could not find the Tarball listed there at all
https://github.com/jlobue10/SteamDeck_rEFInd/releases/tag/v1.2.0

**Comment by jlobue10** [comment]
Yes the tarball from there. The link I sent has further instructions. Please do your best to follow those.

**Comment by jlobue10** [comment]
Are you on the Stable branch and is your SteamOS up to date with the latest build? Any word or progress?

**Comment by darrylmorley** [comment]
I had the same issue, re-imaged the Steam Deck and it worked fine.

**Comment by jlobue10** [comment]
These compile issues should not be an issue moving forward as I will just be compiling myself and uploading the results of `makepkg` using updated `PKGBUILD`.
