### ISSUE TITLE
Uninstall rEFind

### ISSUE THREAD

**Issue by GltichyB** [jlobue10/SteamDeck_rEFInd#72]
i want to remove rEFind from my steam deck

**Comment by jlobue10** [comment]
What a detailed issue... did you try reading and following the instructions?

**Comment by GltichyB** [comment]
yeah i know its very detailed no i didnt i literally just followed a youtube tutorial

**Comment by jlobue10** [comment]
Well if you're going to bother to ask for my help, I'd ask that you at least attempt to follow the instructions from the GitHub README first. If a step doesn't make sense or you get stuck, or have a more specific question, then ask. I can only be as helpful as the information you provide me with. Provide me with minimal information and I can't help too much (garbage in, garbage out).

**Comment by GltichyB** [comment]
nvm i found the instructions
