### ISSUE TITLE
gui suddenly stops working.

### ISSUE THREAD

**Issue by KaidenSkywalker** [jlobue10/SteamDeck_rEFInd#73]
The gui on steamos suddenly stopped working after 2 days of being instslled. the boot menu still works tho so idfk.

**Comment by jlobue10** [comment]
I need more information than this. Were you able to compile the GUI successfully, or did you install one of the precompiled versions? What happens if you try to launch the GUI from the command line?

**Comment by KaidenSkywalker** [comment]
When I did compile the gui using the recommended method there were no errors. Now when I do it though it says there was a fatal error “string”. When I try and launch the gui using the desktop shortcut and .sh file it just doesn’t load.

**Comment by KaidenSkywalker** [comment]
In file included from main.cpp:1:
mainwindow.h:4:10: fatal error: string: No such file or directory
    4 | #include <string>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:797: main.o] Error 1

GUI compile failed. Please try again after ensuring that your cloned repo is up to date and your pacman config is normal.

**Comment by jlobue10** [comment]
Could you try the precompiled versions (both regular and standalone)? Looks like a package dependency problem. I'm honestly growing to hate the immutability and inflexibility of SteamOS if necessary packages aren't included by default in their build. Hopefully one of those precompiled versions works for you. Instructions are on the GUI README page.

**Comment by KaidenSkywalker** [comment]
neither are working unfortunatly. still getting tbe same issue.

**Comment by KaidenSkywalker** [comment]
/home/deck/.SteamDeck_rEFInd/GUI/rEFInd_GUI: /usr/lib/libc.so.6: version `GLIBC_2.36' not found (required by /home/deck/.SteamDeck_rEFInd/GUI/rEFInd_GUI)
/home/deck/.SteamDeck_rEFInd/GUI/rEFInd_GUI: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /home/deck/.SteamDeck_rEFInd/GUI/rEFInd_GUI)
/home/deck/.SteamDeck_rEFInd/GUI/rEFInd_GUI: /usr/lib/libc.so.6: version `GLIBC_2.35' not found (required by /home/deck/.SteamDeck_rEFInd/GUI/rEFInd_GUI)

got this error when trying to run the gui in konsole.

**Comment by jlobue10** [comment]
Thanks for the detailed log. I'll have to look into a different compiling method that's more exhaustive for the standalone (static library) version. Unfortunately I've never been able to replicate these errors on my end.

**Comment by jlobue10** [comment]
Can you tell me the output of this command for you from a SteamOS terminal?

`pacman -Qo /usr/lib/libc.so.6`

If it does not find this file, did the `glibc` package install correctly from the GUI installation script?

**Comment by KaidenSkywalker** [comment]
the output is /usr/lib/libc.so.6 is owned by glibc 2.33-5

**Comment by jlobue10** [comment]
If you run these commands
```
sudo steamos-readonly disable
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Sy glibc lib32-glibc
```
do those 2 packages actually install (and update) or is there an error?

**Comment by KaidenSkywalker** [comment]
The commands broke my deck and I can’t control using the touchpads but on the last command I got this error
![Uploading image.jpg…]()

**Comment by jlobue10** [comment]
Nothing about those commands should "break" your deck. They are just trying to install some software packages that the GUI needs to function.

**Comment by KaidenSkywalker** [comment]
Restarted it and it works just fine now lol

**Comment by KaidenSkywalker** [comment]
:: Synchronizing package databases...
 jupiter.db failed to download
 holo.db failed to download
 core.db failed to download
 extra.db failed to download
 community.db failed to download
error: failed retrieving file 'core.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'jupiter.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'holo.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
warning: too many errors from steamdeck-packages.steamos.cloud, skipping for the remainder of this transaction
error: failed retrieving file 'extra.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'community.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)
(1)(deck@steamdeck ~)$

**Comment by jlobue10** [comment]
Are you on the stable branch of SteamOS?

If you look at your pacman config file with `nano /etc/pacman.conf` is there a portion like this?

```
[jupiter-rel]
Include = /etc/pacman.d/mirrorlist
SigLevel = Never

[holo-rel]
Include = /etc/pacman.d/mirrorlist
SigLevel = Never

[core-rel]
Include = /etc/pacman.d/mirrorlist

[extra-rel]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community-rel]
Include = /etc/pacman.d/mirrorlist

[multilib-rel]
Include = /etc/pacman.d/mirrorlist
```
Or does it look differently?

**Comment by KaidenSkywalker** [comment]
I am on the stable branch, but I wasnt on the latest version. After updating it the gui works. Don't know why updating it could've fixed it but i guess it did.

**Comment by jlobue10** [comment]
> I am on the stable branch, but I wasnt on the latest version. After updating it the gui works. Don't know why updating it could've fixed it but i guess it did.

Updating SteamOS likely fixed whatever lingering package dependency problems existed on your system with my GUI. Thank you for following up with what fixed the issue for you. I guess I am naive in assuming that everyone just updates to the latest SteamOS build before installing other software. This will be one of the first questions I ask next time.

Closing as resolved.
