### ISSUE TITLE
Windows reinstallation question 

### ISSUE THREAD

**Issue by Ghardir11** [jlobue10/SteamDeck_rEFInd#75]
Hello 
I need to reinstall Windows and i have some questions to you because im totally green with that. 

This is steps what i need to do. Please tell me that this is Good Road to reinstallation Windows.

1. remove Windows partition.
2. Create Windows partition.
3. Disable refind sudo efibootmgr -b XXXX -A
4. Enable windows efi sudo efibootmgr -b YYYY -a
5. Install windows. 

And All working ? Or i need to do other steps too?

**Comment by jlobue10** [comment]
You can leave the Windows partitions intact and let the Windows installer format with the installation or you can remove the Windows oartitions and leave it as unallocated space for the installer.

Perform those `efibootmgr` steps from the SteamOS recovery USB (or another live Linux USB) to ensure they work properly. Then you should be clear to reinstall.
