### ISSUE TITLE
Cannot boot into Win11 installed on the SD card

### ISSUE THREAD

**Issue by sazabidesu** [jlobue10/SteamDeck_rEFInd#77]
I followed the tutorial to have Win11 Installed on the Steam Deck's SD card. I can manually boot into Windows without any issues. But it appears that rEFInd cannot find the boot partition on the SD card, as it will give an error whenever I select the Windows option at boot menu.
I tried editing the `refind.conf ` like the guide indicated, by adding the UUID from the boot partition using KDE Partition manager, then adding it manually next to `volume UUID (path to efi boot file)`. Then I did use the UI to install the config, but then to no avail, it doesn't work. 
Any advice would be greatly appreciated.

**Comment by jlobue10** [comment]
Please show me what `sudo nano /esp/efi/refind/refind.conf` looks like

**Comment by sazabidesu** [comment]
Thanks for your answer, I actually did edit it under the very same directory, then just pressed the installation button.

<img width="588" alt="image" src="https://github.com/jlobue10/SteamDeck_rEFInd/assets/112148372/c893fae9-fd33-4c58-b79d-b7ee25c8b6d7">

**Comment by jlobue10** [comment]
I think I see the problem. The loader line should be on its own line after the volume line. Make that change and try again.

**Comment by sazabidesu** [comment]
Oh, so it should be:
volume (UUID)
loader (path to EFI file)

Am I right?

**Comment by jlobue10** [comment]
Yes, that's correct. If you're using the GUI and `hwinfo` is properly installed, then the GUI automatically does this for you, as long as the Micro SD card is inserted for the create config step (then install it afterwards).

**Comment by sazabidesu** [comment]
Thanks for quick reply. I'm not sure if `hwinfo` is installed. But when I followed the tutorial and only used the GUI it never worked, that's when I began touching the file directly.

**Comment by jlobue10** [comment]
From command line you can run `which hwinfo` to find that answer. There are steps to install it on my GUI readme page, but perhaps SteamOS is blocking that now or there are repository issues...

**Comment by sazabidesu** [comment]
Sadly, I didn't have hwinfo installed. When I followed the readme steps, the last one fails.

<img width="596" alt="image" src="https://github.com/jlobue10/SteamDeck_rEFInd/assets/112148372/a0324820-2641-4a87-8a31-865e80333603">
This happens when I run `sudo pacman -Sy --noconfirm hwinfo`

**Comment by jlobue10** [comment]
SteamOS repository and immutability shenanigans strikes again. When I coded this months ago, it worked without issues in my testing. Hwinfo was chosen because it didn't need `sudo` perms to grab thos info.

But you're on the right track to just hand edit the file and install it. Thanks for trying to install `hwinfo`.

**Comment by sazabidesu** [comment]
No problem! Thank you for teaching and building this amazing tool. I'm going to show you how I edited it, as it didn't work when I tried it.

![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/112148372/36558d9b-85ad-4203-a1f6-a2f6ef4f30ab)

**Comment by jlobue10** [comment]
Dumb question, but did you actually install it after you edited it?

**Comment by sazabidesu** [comment]
You made me doubt myself, lol. Is there a way to check without restarting?

**Comment by jlobue10** [comment]
I edited my comment. Run that command from above.

**Comment by sazabidesu** [comment]
<img width="581" alt="image" src="https://github.com/jlobue10/SteamDeck_rEFInd/assets/112148372/bbddd7e1-cb75-4cb8-9913-ebd1498ad879">


This is how it looks. It appears, the installation was successful. Let me try to boot.

**Comment by sazabidesu** [comment]
Sadly, this is what it says.

`Ivalid loader file!`
`Error: Not Found while loading bootmgfw.efi`

Hit any key to continue

**Comment by jlobue10** [comment]
Can you boot into the Windows from SD card if you select it from the BIOS? I'm starting to suspect a possibly corrupted or broken SD card, because everything looks correct now.

**Comment by sazabidesu** [comment]
Certainly, It works flawlessly.

**Comment by sazabidesu** [comment]
The Windows installation was done using Rufus, while selecting the Windows Go option. Then just booted directly on the SD card. I also ran the script on Windows afterward.

**Comment by jlobue10** [comment]
Can you show me the output of `efibootmgr`?

**Comment by sazabidesu** [comment]
<img width="585" alt="image" src="https://github.com/jlobue10/SteamDeck_rEFInd/assets/112148372/a99b9aa8-594b-4398-a76d-edfec2699461">

This is how it looks.

**Comment by jlobue10** [comment]
Yep I see it there. We can try a few things. You can see the UUID in that `efibootmgr` output but it's lower case. Try copying and pasting that into the config file and make sure there are no spaces at the end of that line (no trailing whitespace). This is definitely strange though. I may need to double check on my Steam Deck. It worked flawlessly when I tested it months ago.

**Comment by sazabidesu** [comment]
Will try this and get back to you.

**Comment by sazabidesu** [comment]
Update, I ended changing all /// bars to \\\\ in the EFI path just to try. Somehow it works! 
I'm not really sure if that was the culprit. For example, when I managed to boot into Windows, I continue to set it up, to the point it wanted to install updates, I then restarted and that's when the boot would not work again, giving the same error as before. Went back to Steam OS, shut the deck off, turned it on, and guess what, it booted into windows without problem.

**Comment by jlobue10** [comment]
I suspect that you probably had extra spaces at the end of the volume line which likely would have been the same as a typo. Either way, I'm happy that you fixed it. If you can try to get `hwinfo` package installed properly, then the GUI could handle that automatically for you in the future.

There might also be a better way to grab that partition UUID info for the GUI config file generation than `hwinfo`, by using a pre-installed SteamOS package. I don't have the time to look into that for now though.
