### ISSUE TITLE
Windows being added to the boot menu automatically every time I enter the boot menu

### ISSUE THREAD

**Issue by mrkaspa** [jlobue10/SteamDeck_rEFInd#79]
Every time I enter the boot menu I get a windows entry after installing, I removed all this steamdeck refind package but I have had no luck with this every time  I have this issue I must enter in desktop mode and remove the efi entry in the CLI, I already uninstalled windows I am trying to revert all the process, do you know how can I disable the creation of the windows boot entry automatically?

**Comment by jlobue10** [comment]
Firmware is likely re-adding it  if the `Microsoft` folder still exists on your `/esp` partition. You need to delete that `Microsoft` folder and then manually remove that efi entry one last time.

**Comment by mrkaspa** [comment]
it worked thank you!
