### ISSUE TITLE
error:Unsupported while loading steamcl.efi.

### ISSUE THREAD

**Issue by ypl7** [jlobue10/SteamDeck_rEFInd#8]
Selecting steam os to enter only flashes the screen, and at the same time there is a message 
error:Unsupported while loading steamcl.efi.

**Comment by jlobue10** [comment]
What branch of SteamOS are you trying to boot? I have not experienced this error with the stable branch.

**Comment by ypl7** [comment]
I solved the problem after reinstalling the system.

**Comment by jlobue10** [comment]
Can you elaborate in case somebody else has this issue in the future? Did you reimage or reinstall SteamOS from the recovery image?

**Comment by ktetreault** [comment]
I am on latest beta (3.4) and did not experience issues with a reinstall and bootup. After I installed 3.4 though I found myself unable to boot and manually used the BIOS to boot to the correct efi file for my rEFInd setup. then I was able to boot into SteamOS and reinstall rEFInd using this script. Successfully rebooted also

**Comment by jlobue10** [comment]
@ktetreault Did you have rEFInd working properly before switching to 3.4? For the sake of being thorough, I'd like to know this as quite a few people reach out to me for troubleshooting, and this would be helpful information to know. I think if people do not have rEFInd installed before switching to 3.4, then the disable Windows EFI boot entry portion of the script won't work and will require reverting to the stable branch of SteamOS to run the script successfully, before going back to 3.4.

**Comment by ktetreault** [comment]
I had everything working perfect beforehand and was already on the beta
branch

**Comment by jlobue10** [comment]
Thanks for confirming that. Closing this issue
