### ISSUE TITLE
Setup _rEFInd Fails in Windows

### ISSUE THREAD

**Issue by darrylmorley** [jlobue10/SteamDeck_rEFInd#81]
Hi,

I have no access to the boot screen and running the Windows script fails with the error: Incorrect Parameter

**Comment by jlobue10** [comment]
This is not enough information for me to be helpful... did you complete the setup on Linux side? The main thing the script accomplishes on the Windows side is allowing you to not have to disable Windows' efi entry for rEFInd to work. That's all (more or less).

**Comment by darrylmorley** [comment]
Yes the setup was completed on the Linux side. I'll look into disabling the Windows EFI. I recognise that there's not much to go on.
