### ISSUE TITLE
Doesn’t give option for Desktop icon

### ISSUE THREAD

**Issue by Udasrt8** [jlobue10/SteamDeck_rEFInd#85]
After installing on steam deck, I see where others get an option to have desktop icon. However my install did not give me that option and I’m unable to use it. The 1st steam deck worked fine. But the 2nd steam deck will not give the option for an icon. Granted the 1st steam deck had it installed a month ago. The second one that isn’t working is current 11/15/23. I’ve uninstalled and reinstalled. No icon option is given.

**Comment by jlobue10** [comment]
I believe the icon and shortcut should still be there. Can you please open Dolphin file explorer and navigate to `/home/deck/Desktop` and see if it's there in Dolphin? I think this might be an artifact of the updated curl install method and I need to debug why this is happening. For now, just please manually copy it to your desktop from that folder (if it's there).

**Comment by jlobue10** [comment]
I updated the script with a minor change. I thin
