### ISSUE TITLE
rEFInd GUI not Installing Config

### ISSUE THREAD

**Issue by Jotaido** [jlobue10/SteamDeck_rEFInd#86]
As the title says, I try to create a config and install it but it doesn't work, I think it should ask for the password again but it doesn't even ask for it. rEFInd works fine but because of that I can't change the icons so I have 2 weird yellow triangles like there's an error instead of Steam and Windows icons (I don't know if there's a way to change them manually)

**Comment by jlobue10** [comment]
3.5 seems to have broken some stuff. I am debugging and looking into a better installation solution moving forward with PKGBUILD. No exact eta yet, but I am actively working on it.

**Comment by dtantono** [comment]
yeah I tried reinstall the GUI again with the command line. But, it does not working

**Comment by jlobue10** [comment]
Please try again with the updated installer. It's working well for me now.

**Comment by Jotaido** [comment]
It works perfect now, thank you for everything!

**Comment by jlobue10** [comment]
Thanks for confirming. I'm happy I was able to get this all fixed and repackaged (appropriately) fairly quickly. Closing the issue.
