### ISSUE TITLE
New Install gives errors and doesn't give a rEFInd boot option

### ISSUE THREAD

**Issue by shhada** [jlobue10/SteamDeck_rEFInd#89]
while trying to install rEFInd, i get the following errors:
`error: refind: signature from "David Runge <dvzrv@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/refind-0.13.3.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
sudo: refind-install: command not found`

this gives me no GUI on the desktop and no boot option for rEFInd at all. any ideas?
p.s. i never hit y or n when that prompt popped up

**Comment by shhada** [comment]
update: tried out the new GUI installation method and it worked flawlessly. no issues, no errors, nothings missing. i most definitely should have tried that before opening up this issue, but hopefully this could help someone else in the future as well

**Comment by jlobue10** [comment]
Is there some reason you aren't upgrading to 3.5.5? The new installation method has been developed and tested for SteamOS 3.5.5 and later versions.

**Comment by shhada** [comment]
> Is there some reason you aren't upgrading to 3.5.5? The new installation method has been developed and tested for SteamOS 3.5.5 and later versions.

i set it to automatically update but i guess it just hasn't yet. i'll be trying it out shortly

**Comment by shhada** [comment]
update: installed SteamOS 3.5.5 and now both rEFInd _and_ SteamOS boot options are not showing up, only windows boot manager

**Comment by jlobue10** [comment]
Reboot into SteamOS manually through its EFI file. This is a known issue with BIOS updates wiping EFI entries. If you had the `bootnext-refind.service` active, the missing EFI entries will be re-created automatically.

**Comment by shhada** [comment]
> Reboot into SteamOS manually through its EFI file (Vol+ and power to get into BIOS). This is a known issue with BIOS updates wiping EFI entries. If you had the `bootnext-refind.service` active, the missing EFI entries will be re-created automatically upon boot into SteamOS.

that worked flawlessly, thanks!! just had to apply a [dual boot fix](https://www.mediafire.com/file/w7jswsuctvnnd7k/Dual+Boot+Fix.zip/file) and everything worked fine

**Comment by jlobue10** [comment]
Sounds good. Please close the issue if you're happy with the resolution.
