### ISSUE TITLE
Refind problem after new steam on update

### ISSUE THREAD

**Issue by Ghardir11** [jlobue10/SteamDeck_rEFInd#90]
Hello I have a problem with dual boot screen after update steam os.

When I start steam os and close after next start I have dual boot screen. But when I open windows and then close after start steam deck I dont have dual boot screen just steam os loading automatically.

Do you know what happened?

Maybe this is by this command from reddit. sudo efibootmgr -c -d /dev/nvme0n1 -p 1 -L "SteamOS" -l "\EFI\steamos\steamcl.efi"

I used this when steam deck not booting

**Comment by dtantono** [comment]
I noticed this the refind GUI menu is gone

**Comment by Ghardir11** [comment]
I have gui but only if I close steam os. If close windows I don’t have gui and steam os loading automatically

**Comment by dtantono** [comment]
I mean on steamos desktop. the gui icon is gone

**Comment by Ghardir11** [comment]
For me its not disappeared. Only dual boot screen

**Comment by jlobue10** [comment]
Are you using the updated version? I completely re-did the process this past weekend.

**Comment by Ghardir11** [comment]
Im using older one probably but why if I close steam os I have dual boot screen but when I close windows 11 then steam os loading without dual boot screen. Maybe I need disable and enable refind?

**Comment by Ghardir11** [comment]
![IMG_0855](https://github.com/jlobue10/SteamDeck_rEFInd/assets/127780027/f0e0d610-3955-4359-a767-8e63cffcea77)

**Comment by jlobue10** [comment]
Please install latest release, perform the install rEFInd step with Sourceforge as the source, and then redo the create config and install config steps, and see if the issue is fixed or not.

**Comment by Ghardir11** [comment]
Can you tell me step by step how to do it I’m totally green just used YouTube tutorial to make dual boot. I need to uninstall my one ?

**Comment by Ghardir11** [comment]
git klon https://github.com/jlobue10/SteamDeck_rEFInd/ cd SteamDeck_rEFInd chmod +x SteamDeck_rEFInd_install.sh . /SteamDeck_rEFInd_install.sh

This working ? I can do this ? I need to uninstall my one ?

**Comment by jlobue10** [comment]
Please try the updated GUI installer. I added some stuff to auto clean up old installations.

[Here](https://github.com/jlobue10/SteamDeck_rEFInd/tree/main#updated-installation-method-is-steamos-35-compatible-an-optional-background-randomizer-feature-has-been-added)

**Comment by Ghardir11** [comment]
I need just type this in console ? I typed similiar  script when I used tutorial from YouTube 

git clone https://github.com/jlobue10/SteamDeck_rEFInd/
cd SteamDeck_rEFInd
chmod +x SteamDeck_rEFInd_install.sh
./SteamDeck_rEFInd_install.sh

**Comment by jlobue10** [comment]
No that's the old, pre-GUI method.

**Comment by jlobue10** [comment]
Copy and paste this in Konsole.

```
cd $HOME && rm -rf $HOME/SteamDeck_rEFInd/ && git clone https://github.com/jlobue10/SteamDeck_rEFInd && cd SteamDeck_rEFInd && chmod +x install-GUI.sh && ./install-GUI.sh
```

**Comment by Ghardir11** [comment]
In one line or line by line ?

**Comment by jlobue10** [comment]
Literally copy and paste as one command. The `&&` strings them altogether into one copy and paste. I tried curl but had some issues with that doing everything I wanted correctly.

**Comment by Ghardir11** [comment]
Installed and still the same when close windows I don’t have dual boot screen. Maybe after reinstalling windows also I do something wrong?

**Comment by Ghardir11** [comment]
All ok there ?

![IMG_0856](https://github.com/jlobue10/SteamDeck_rEFInd/assets/127780027/a013df1e-ac5f-45a4-8ee3-d1901cf3acdf)

**Comment by jlobue10** [comment]
What does your rEFInd config file look like? `sudo nano /esp/efi/refind/refind.conf`

**Comment by Ghardir11** [comment]
![IMG_0858](https://github.com/jlobue10/SteamDeck_rEFInd/assets/127780027/7e80c284-1472-4410-80ad-de5801b9ffa1)

**Comment by jlobue10** [comment]
If you can download the zip of this repository and go to Windows. Inside the `Windows/Install rEFInd` folder please run the `Setup_rEFInd_Windows_RunAsAdmin.bat` as administrator and try again. This will hopefully solve your issue.

**Comment by Ghardir11** [comment]
What I need to download ? And where type these commands. In console of steam os ?

**Comment by jlobue10** [comment]
GO into Windows and download this zip file [here](https://github.com/jlobue10/SteamDeck_rEFInd/archive/refs/heads/main.zip). Unzip it and inside the Windows folder, you will find the script I mentioned to right click and run as admin. Then reboot and try again to see if your issue is fixed.

**Comment by Ghardir11** [comment]
I came find this file name in package Setup_rEFInd_Windows_RunAsAdmin.bat

**Comment by Ghardir11** [comment]
still the same but first time when closed windows dual boot showed. But next time not showed and steam os automatically loaded

**Comment by Cinere** [comment]
Tell me, the boot will be reset with each BIOS update, I have SteamOS and Windows, and for the second time after the update, Steamos erased its boot. In addition, this time it was not possible to restore the system data. How can this be avoided? In theory, I could move the Windows boot from first place. Then you will need to restore only the Windows boot and not two.

**Comment by Cinere** [comment]
> все то же самое, но впервые после установки сценария, когда при закрытых окнах показывалась двойная загрузка. Но в следующий раз ничего не показывалось, и Steam автоматически загружался.

Try reinstalling the refind in Linux again, and then opening it, first apply the dual boot settings depending on the configuration of the systems (usually it determines where what is), press three buttons in turn, making sure that after pressing each, the process of applying the settings has been completed. After applying the settings without changes, reboot the steam deck, dual boot should appear, to customize, first apply the necessary changes and then repeat pressing the buttons below
![Uploading фввфвфв.png…]()

**Comment by Ghardir11** [comment]
Can someone help me ?

**Comment by Ghardir11** [comment]
Hellowhat changes in windows give this 

„Inside the Windows/Install rEFInd folder please run the Setup_rEFInd_Windows_RunAsAdmin.bat as administrator and try again. This will hopefully solve your issue.”

**Comment by jlobue10** [comment]
And based off his `efibootmgr` and `re find.conf` views earlier, a couple of things are contributing to this weirdness. The boot order is not what I'd expect it to be from a normal rEFInd installation. I'd personally probably (manually) remove the rEFInd EFI entry with `sudo efibootmgr -b 0001 -B and re-run the Sourceforge installer script, followed by create config and then install config from my GUI.

The Windows side script was a way for raeFInd to be set as the default next boot target. It's still a good idea in my opinion to use it (even if Windows EFI entry has been disabled).

I need to make a minor new release today to fix up pointers to scripts (need to move away from `/usr/bin`).

Deck Wizard is working on an updated dual boot video if you really must have a video for assistance (by the way).

**Comment by Cinere** [comment]
> Deck Wizard is working on an updated dual boot video if you really must have a video for assistance (by the way).

There will be a solution to the problem of resetting the Steam OS boot file. I used his latest video for installation, it was very convenient and quite easy. But because of Windows and BIOS updates, everything goes away

**Comment by jlobue10** [comment]
BIOS updates on the Deck wipe EFI entries. The only way to fix this problem is for Valve themselves to address that. This has been an issue for many months now (not a new phenomenon).

**Comment by Cinere** [comment]
Then you need to look at how to remove EFI Windows and Refind before installing the Windows update. To install updates correctly, and then restore one and another boot, this is much faster than restoring everything if an error occurs. Moreover, I haven’t found a working way to restore my Windows boot if it crashes.

**Comment by Cinere** [comment]
> Then I need to look at how to remove EFI Windows and Refind before installing the Windows update. To install updates correctly, and then restore one and another boot, this is much faster than restoring everything if an error occurs. Moreover, I haven’t found a working way to restore my Windows boot if it crashes.

**Comment by jlobue10** [comment]
> Then you need to look at how to remove EFI Windows and Refind before installing the Windows update. To install updates correctly, and then restore one and another boot, this is much faster than restoring everything if an error occurs. Moreover, I haven’t found a working way to restore my Windows boot if it crashes.

EFI entries are already recreated if they are missing for SteamOS and rEFInd with my existing `systemd` service. I can't personally create a better solution than that. To recreate missing Windows boot files and entry, I have that covered here.

**Comment by Ghardir11** [comment]
For me it helped  step 1 2 3

![IMG_0865](https://github.com/jlobue10/SteamDeck_rEFInd/assets/127780027/1c5d5d20-52eb-4b81-8e40-424aa44a5817)
now I have dual boot screen when close windows. So I don’t know where was the problem

**Comment by Cinere** [comment]
> EFI entries are already recreated if they are missing for SteamOS and rEFInd with my existing `systemd` service. It requires a manual boot into SteamOS with the service running. I can't personally create a better solution than that. To recreate missing Windows boot files and EFI entry, I have that covered [here](https://github.com/jlobue10/SteamDeck_rEFInd/issues/49).

Yes, I restored the Windows bootloader, but the  reinstall SteamOS with the latest major update took everything off the system without saving games, etc., last time everything turned out fine.
It became obvious to me that this is not an option, and I need to think about what measures can be taken before installing a new Steam OS update.

**Comment by Cinere** [comment]
> For me it helped step 1 2 3
> 
> ![IMG_0865](https://user-images.githubusercontent.com/127780027/285486407-1c5d5d20-52eb-4b81-8e40-424aa44a5817.jpeg) now I have dual boot screen when close windows. So I don’t know where was the problem

It happens that while doing everything correctly, it does not install correctly, you just need to repeat all the steps from the very beginning, make sure that everything works and then change the parameters.

**Comment by jlobue10** [comment]
Also, Sourceforge is the recommended installation source at the moment and likely going forward. It's newer than `pacman` rEFInd last time I checked and not as prone to breaking as `pacman` based installation (repo trouble).

**Comment by jlobue10** [comment]
> > For me it helped step 1 2 3
> > ![IMG_0865](https://user-images.githubusercontent.com/127780027/285486407-1c5d5d20-52eb-4b81-8e40-424aa44a5817.jpeg) now I have dual boot screen when close windows. So I don’t know where was the problem
> 
> It happens that while doing everything correctly, it does not install correctly, you just need to repeat all the steps from the very beginning, make sure that everything works and then change the parameters.

From a working installation that got temporarily messed up from a BIOS update, only steps 2 and 3 are really required from your picture. It helped to keep the `systemd` service running too, in order to automatically recreate and missing EFI entries for SteamOS and/ or rEFInd upon boot into SteamOS.
