### ISSUE TITLE
Refind GUI Menu is gone on SteamOS 3.5.7

### ISSUE THREAD

**Issue by dtantono** [jlobue10/SteamDeck_rEFInd#91]
Hi
After OS getting update. it looks like the GUI menu is gone and when I tried to reinstall it back with

 cd $HOME && rm -rf $HOME/SteamDeck_rEFInd/ && git clone https://github.com/jlobue10/SteamDeck_rEFInd && cd SteamDeck_rEFInd && chmod +x install-GUI.sh && ./install-GUI.sh

I got this error. What do you think?

![Screenshot_20231123_230732](https://github.com/jlobue10/SteamDeck_rEFInd/assets/29157187/c94967e9-76aa-44bf-8a7f-46837289fc57)

**Comment by jlobue10** [comment]
Looking into it.

**Comment by jlobue10** [comment]
Please re-run installer. I made a new small release to address this issue persisting across OS updates. Gotta love immutability...

**Comment by dvalv** [comment]
![Screenshot_20231123_180038](https://github.com/jlobue10/SteamDeck_rEFInd/assets/88657185/5eb1f8bb-308c-4999-a087-c86d63326492)

Thats mine, executed a few minutes ago

**Comment by jlobue10** [comment]
Had a typo in install script for clean-up. Fixed now. Please try again.

**Comment by dvalv** [comment]
Working like a charm!

**Comment by dtantono** [comment]
Thanks and it works again
