### ISSUE TITLE
Error with efibootmgr

### ISSUE THREAD

**Issue by DarkrysVakarian** [jlobue10/SteamDeck_rEFInd#94]
Hello,

I just received my New Deck Oled and i tried to install Windows, just like my lcd deck.
Then i install refind via GUI method

But Windows always boot first.
So i tried the "sudo efibootmgr -b XXXX -A" command, either on regular desktop mode and recovery mode and i've got the same error : 
efibootmgr : Boot entry 5 not found
Could not set active state for Boot0005: No such file or directory

Did the efibootmgr still work ?

Thank you

Cordially

**Comment by jlobue10** [comment]
Yes it seems that may actually be broken with the recovery USB now, although I didn't try t with the very latest recovery USB (would like to hear from someone who has).

I did successfully apply that command from a live Kubuntu 23.10 iso though, so it seems distro (or package) dependent to a degree.

**Comment by styler00dollar** [comment]
I ran into the same problem. Downloaded the steam recovery file today. `sudo efibootmgr` shows `Boot0006 Windows Boot manager`, but `sudo efibootmgr -b 0006 -A` results in `Could not set state for Boot0006: No such file or directory`.

**Comment by jlobue10** [comment]
Yes, so I don't know if this is just a bug or being blocked intentionally. For now, what I've been doing is using my MicroSD card slot as Ventoy and keeping various images on there. Booting into live Kubuntu 23.10 allowed me to disable it just fine.

**Comment by jlobue10** [comment]
Can you show me your `efibootmgr` output now?

**Comment by styler00dollar** [comment]
After disabling Windows with Kubuntu it now looks like this. I replaced a few ids to keep it generic.
Kubuntu 22.10:
```
kubuntu@kubuntu:~$ sudo efibootmgr
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0006,0005,0004,0002,2001,2002,2003
Boot0000* EFI PXE 0 for IPv4 (<ID>)
Boot0001* EFI PXE 0 for IPv6 (<ID>)
Boot0002* Linpus lite
Boot0004* SteamOS
Boot0005* rEFInd
Boot0006  Windows Boot Manager
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
```
Afterwards booted into SteamOS live image to show what I mean by different:
```
(deck@steamdeck ~)$ sudo efibootmgr
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0006,0005,0004,2001,2002,2003
Boot0000* EFI PXE 0 for IPv4 (<ID>)        PciRoot(<HEX>)/Pci(<HEX>,<HEX>)/Pci(<HEX>,<HEX>)/USB(1,0)/USB(3,0)/MAC(<MAC ADRESS>,1)/IPv4(0.0.0.00.0.0.0,0,0)RC
Boot0001* EFI PXE 0 for IPv6 (<ID>)        PciRoot(<HEX>)/Pci(<HEX>,<HEX>)/Pci(<HEX>,<HEX>)/USB(1,0)/USB(3,0)/MAC(<MAC ADRESS>,1)/IPv6([::]:<->[::]:,0,0)RC
Boot0002* EFI USB Device     UsbWwid(<ID>,<ID>,0,<ID>)/HD(1,GPT,<UUID>,<HEX>,<HEX>)RC
Boot0004* SteamOS       HD(1,GPT,<UUID>,<HEX>,<HEX>)/File(\EFI\steamos\steamcl.efi)
Boot0005* rEFInd        HD(1,GPT,<UUID>,<HEX>,<HEX>)/File(\EFI\refind\refind_x64.efi)
Boot0006  Windows Boot Manager  HD(1,GPT,<UUID>,<HEX>,<HEX>)/File(\EFI\Microsoft\Boot\bootmgfw.efi)<VERY LONG STRING WITH NUMBERS AND LETTERS>
Boot2001* EFI USB Device        RC
Boot2002* EFI DVD/CDROM RC
Boot2003* EFI Network   RC
```
Since I use one usb stick it takes a while to write new images onto it, so I can only respond with delay.

**Comment by jlobue10** [comment]
Is everything working normally for you now, or is there still an issue? I'd suggest clicking the 'Sysd On' button on the GUI as well. There's no reason really not to in my opinion (I can tell it's off from the `efibootmgr` output from SteamOS).

**Comment by styler00dollar** [comment]
Everything seems to be working properly, didn't need to re-configure anything afterwards. All I did was SteamOS, rEFInd (Install, Create Config, Install Config), Windows10 and then efibootmgr with Kubuntu because other Linux Distros I tried didn't want to run that command.

**Comment by styler00dollar** [comment]
I think this information would be useful to be placed into the readme until there is a proper solution.

**Comment by jlobue10** [comment]
> I think this information would be useful to be placed into the readme until there is a proper solution.

Agreed. I need to update a few other things too in there.
