### ISSUE TITLE
Cannot boot to SteamOS and only boot to Windows

### ISSUE THREAD

**Issue by dnet890** [jlobue10/SteamDeck_rEFInd#96]
Hi
I saw that today there is software update. But, I have strange issue that when I presented with refind boot selector. I cannot boot SteamOS and it's just bouncing back to Refind menu selector and when I select Windows (I can boot to STeamOS with boot from file esp/efi/steamos/steamcl.efi). it works normally. BTW, I tried to delete everything related to refind even the esp file and reinstall it back with cd $HOME && rm -rf $HOME/SteamDeck_rEFInd/ && git clone https://github.com/jlobue10/SteamDeck_rEFInd && cd SteamDeck_rEFInd && chmod +x install-GUI.sh && ./install-GUI.sh I got same issue.

What do you think?

**Comment by jlobue10** [comment]
Still working okay here after updating this morning.

Can you show me output of your `efibootmgr`?

**Comment by dtantono** [comment]
here it is what do you think?
![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/29157187/dcb1d03a-d76f-491f-a971-4677bd8de2bc)

**Comment by jlobue10** [comment]
What I would do in your situation is manually remove the EFI entries for SteamOS and rEFInd and then manually boot back into SteamOS from its EFI file.
```
sudo efibootmgr -b 0000 -B
sudo efibootmgr -b 000A -B
```
Then before rebooting, ensure that 'Sysd On' has been clicked from the GUI and you received a good status from that completing... Reboot and those entries will be recreated. Then open the GUI and redo the create config followed by install config steps.

I'd recommend using the live Kubuntu 23.10 iso to just boot into it and disable your Windows EFI entry with `sudo efibootmgr -b 0001 -A`. After all that, you should be in good shape.

**Comment by dtantono** [comment]
Hi
Thanks for your reply and it is getting better. But, I have questions:
1. Now the refind works better. Is it important to disable Windows bootloader. on SteamOS or separate Linux distros? 
2. I saw besides the boot entry number there are some of them marked with asterisk/star. But some aren't. What is that mean?
3. I saw my Windows boot manager is multiplied. Is that okay?

![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/29157187/be562dff-fa24-4d8d-8e3e-d3e74acc8de5)

**Comment by jlobue10** [comment]
Asterisk denotes whether en entry is active or not. A missing asterisk means that entry is not active. I'd probably delete the 0001 duplicate Windows entry `sudo efibootmgr -b 0001 -B`. I suggested the other Linux for it because the ability to do that from SteamOS has been broken since 3.4+ . Also, the SteamOS recovery USB doesn't work to do that either right now.

**Comment by dtantono** [comment]
this is strange I already deleted it (sudo efibootmgr -b 0001 -A) on Kubuntu live boot. But, when I go back to SteamOS via refind. it just comes back. Should I ignore it?
![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/29157187/22d1a9d5-5531-4d4a-8e10-eb23290fd721)

**Comment by jlobue10** [comment]
`-A` disabled the entry. `-B` delete it. I think you disabled it, not deleted it.

**Comment by dtantono** [comment]
yeah, the boot order change like this and I think it should be stable for a while. what do you think?
![image](https://github.com/jlobue10/SteamDeck_rEFInd/assets/29157187/d0963e56-021e-4650-9643-992990a2a02a)

**Comment by dtantono** [comment]
yeah it works well and thanks for your help

**Comment by jlobue10** [comment]
No problem.
