### ISSUE TITLE
Issues installing GUI for SteamDeck via rEFInd

### ISSUE THREAD

**Issue by JimmyDonuts** [jlobue10/SteamDeck_rEFInd#98]
So I'm going to start this off by saying I'm not very experienced with Linux, coding or github at all, but my brother recently bought himself a SteamDeck (non OLED, but it is the 256gb version) and he asked me if i could put Windows on it so he can play CoD. I said sure ez. Not ez enough for me. i watched a video called "How to Dual Boot Steam Deck" by a channel called Deck Wizard. I was following all the steps until i realized that the github repository has changed since the video was made. So, I just tried to follow along as best as i could with the video, but im unsure how to move forward with the GUI installation. Do i still copy and paste things "line by line"? Do i do it all at once? I really don't want to mess this up, can somebody please help?

**Comment by jlobue10** [comment]
Yes, since that set of videos, and since the release of SteamOS 3.5 and the OLED Steam Deck, I have drastically improved the installation process of this GUI. THe one long string of chained commands is intended to be a one time copy and paste thing to do. You will be prompted for a `sudo` (your deck username) password and that's it. It just works after the installation. The rest of the steps in his video tutorials are still relevant. Please don't be afraid or hesitant to ask any other questions that you may have. Thanks.

**Comment by JimmyDonuts** [comment]
Okay great, thanks for the response! I did have one last question/concern. So i ran the code before i installed windows, and i never got the Y/N prompt to make a rEFInd GUI shortcut, so i'm unsure if i actually did it right. So i just decided to load windows on it. So basically my question is once i load in all the windows drivers and go back to SteamOS do i run the code again to get the GUI shortcut?

**Comment by jlobue10** [comment]
You don't need to run it again. The installer just automatically adds the icon to desktop now too.

**Comment by JimmyDonuts** [comment]
I only ran it the one time, and the only icon i got onto the desktop is SteamDeck_rEFInd, is the GUI in there or???

**Comment by jlobue10** [comment]
That is the GUI icon. I did a lot of updates and i just decided to make it match the repo name. I fixed some minor graphical issues with it this morning too. It should be good to go. Please let me know if you have any other questions.

**Comment by JimmyDonuts** [comment]
yup you're right, after Windows was installed i went back to click on the icon and it worked! Thanks so much for taking the time to answer my questions!
